(()=>{'use strict';
const K='afak_horizon_v2',OLD='afak_mobile_v12',OV8='afak_platform_v8',OS='afak_settings_v15',OP='afak_packs_v14';
const uid=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),today=()=>new Date().toISOString().slice(0,10);
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),money=x=>{let n=Number(x||0);if(!Number.isFinite(n))n=0;let s=Math.abs(n).toFixed(2).replace('.',',').replace(/\\B(?=(\\d{3})+(?!\\d))/g,' ');return(n<0?'-':'')+s+' دج'};
const parseMoney=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim().replace(/ دج/g,'').replace(/\s/g,'').replace(',','.');let n=Number(s);return Number.isFinite(n)?n:0};
const moneyInput=(id,v='')=>'<div class="field moneyfield"><label>المبلغ</label><input id="'+id+'" inputmode="decimal" type="text" value="'+esc(v===''?'':parseMoney(v).toFixed(2).replace('.',','))+'" placeholder="0,00"><small class="mut">دج</small></div>';
const formatMoneyInput=(e,finalize=false)=>{let el=e?.target||e;if(!el)return;let raw=String(el.value||'').replace(/[^0-9,.-]/g,'');if(raw.includes('-'))raw=(raw[0]==='-'?'-':'')+raw.slice(1).replace(/-/g,'');let parts=raw.replace('.',',').split(',');let whole=parts[0]||'';let dec=(parts[1]||'').replace(/\D/g,'').slice(0,2);if(finalize){let n=parseMoney(raw);el.value=n.toFixed(2).replace('.',',')}else{el.value=whole+(raw.includes(',')?','+dec:'')}};
const bindMoneyInput=id=>{let el=document.getElementById(id);if(!el)return;el.addEventListener('input',e=>formatMoneyInput(e,false));el.addEventListener('blur',e=>formatMoneyInput(e,true))};
const settingsDefault={membershipTypes:['عضو مؤسس','عضو عامل','عضو منخرط','عضو شرفي','متطوع','رياضي','مدرب/مؤطر','حكم'],paymentMethods:['نقدًا','صك/شيك','تحويل CCP','تحويل بنكي','BaridiMob','الدفع الإلكتروني','أخرى'],accounts:['الصندوق','CCP','البنك','الحساب الإلكتروني','أخرى'],activityTypes:['الطيران الشراعي','الطيران الشراعي بمحرك','النماذج الجوية','المشي الجبلي','التخييم','التسلق','نشاط آخر'],statuses:['مبرمج','قيد التنفيذ','منجز','ملغى','مؤجل'],eventTypes:['تدريب','خرجة جبلية','تخييم','فعالية/تظاهرة','اجتماع/تنسيق','أخرى'],roles:['مشارك','متدرب','رياضي','مؤطر','منظم','متطوع','مسؤول','أخرى'],years:['2025','2026'],memberTableColumns:['الرقم','الاسم','تاريخ الميلاد','مكان الميلاد','الهاتف','البريد الإلكتروني','الإقامة','رقم الطوارئ','الصفة','حالة العضوية']};
const activityCatalogDefault=[{code:'B',name:'النماذج الجوية',pack:'B',order:1,active:true},{code:'C',name:'المشي الجبلي والتخييم',pack:'C',order:2,active:true},{code:'D',name:'الطيران الشراعي',pack:'D',order:3,active:true},{code:'E',name:'الطائرات النموذجية والطائرات بدون طيار',pack:'E',order:4,active:true},{code:'F',name:'الطيران الشراعي بمحرك',pack:'F',order:5,active:true}];
const packsDefault={A:{d:'الاشتراك القانوني لغير الممارس',v:1000,p1:100,p2:0},B:{d:'اشتراك ممارس النماذج الجوية',v:4000,p1:50,p2:50},C:{d:'اشتراك ممارس المشي الجبلي والتخييم',v:5000,p1:50,p2:50},D:{d:'اشتراك ممارس الطيران الشراعي',v:15000,p1:50,p2:50},E:{d:'اشتراك ممارس الطائرات النموذجية والطائرات بدون طيار',v:30000,p1:50,p2:50},F:{d:'اشتراك ممارس الطيران الشراعي بمحرك',v:35000,p1:50,p2:50}};
function fresh(){return{schema:'1.0',members:[],memberships:[],transactions:[],plans:[],activities:[],participants:[],attendance:[],equipment:[],incoming:[],outgoing:[],correspondence:[],meetings:[],decisions:[],tasks:[],documents:[],audit:[],years:{'2025':{status:'open',opening:0},'2026':{status:'open',opening:0}},settings:settingsDefault,packs:packsDefault}}
function load(){let n=JSON.parse(localStorage.getItem(K)||'null');if(n)return n;let o=JSON.parse(localStorage.getItem(OLD)||'null')||{},v=JSON.parse(localStorage.getItem(OV8)||'null')||{},d=fresh();d.members=o.members||[];d.memberships=o.memberships||[];d.transactions=(o.finance||[]).map(x=>({...x,id:x.id||uid('OP'),kind:x.type==='مصروف'?'دفع':'قبض',year:String(x.financialYear||String(x.date||'').slice(0,4)||'2026'),description:x.desc||x.description||'',category:x.category||''}));d.activities=o.activities||[];d.participants=o.participation||[];d.attendance=o.attendance||[];d.equipment=v.assets||[];d.plans=v.plans||[];d.correspondence=v.correspondence||[];d.meetings=v.meetings||[];d.decisions=v.decisions||[];d.tasks=v.tasks||[];d.documents=v.documents||[];d.audit=v.audit||[];d.years=v.yearMeta||d.years;d.incoming=JSON.parse(localStorage.getItem('afak_incoming_mail_v19')||'[]');d.outgoing=JSON.parse(localStorage.getItem('afak_outgoing_mail_v19')||'[]');d.settings=JSON.parse(localStorage.getItem(OS)||'null')||settingsDefault;d.packs=JSON.parse(localStorage.getItem(OP)||'null')||packsDefault;localStorage.setItem(K,JSON.stringify(d));return d}
let db=load();db.settings={...settingsDefault,...(db.settings||{})};db.packs={...packsDefault,...(db.packs||{})};
if(!Array.isArray(db.activityCatalog)||!db.activityCatalog.length)db.activityCatalog=activityCatalogDefault.map(x=>({...x}));
if(!Array.isArray(db.settings.memberTableColumns)||!db.settings.memberTableColumns.length)db.settings.memberTableColumns=settingsDefault.memberTableColumns.slice();
const packTotal=p=>p?.code==='A'?Number(db.packs.A?.v||0):(Number(db.packs.A?.v||0)+Number(p?.insurance||0)+Number(p?.equipment||0));
Object.entries(db.packs).forEach(([k,p])=>{p.code=k;if(k==='A'){p.legal=true;p.insurance=0;p.equipment=0}else{if(p.insurance==null)p.insurance=Math.max(0,Math.round((Number(p.v||0)-Number(db.packs.A?.v||0))/2));if(p.equipment==null)p.equipment=Math.max(0,Number(p.v||0)-Number(db.packs.A?.v||0)-Number(p.insurance||0));p.v=packTotal(p)}});
function activeActivities(){return db.activityCatalog.filter(x=>x.active!==false).sort((a,b)=>(a.order||0)-(b.order||0))}
function activityByCode(code){return db.activityCatalog.find(x=>String(x.code)===String(code))}function isFrozen(m,code){return !!(m.practiceFreeze&&m.practiceFreeze[code])}function practiceLabel(m,r,c,a){if(isFrozen(m,a.code))return{status:'مجمد',active:false};if(!c.practiceActive)return{status:c.practiceStatus,active:false};return{status:'مسموح',active:true}}
function packRank(code){let order=['B','C','D','E','F'];let i=order.indexOf(String(code));return i<0?999:i}function eligibleActivities(packCode){if(packCode==='A'||!packCode)return[];let rank=packRank(packCode);return activeActivities().filter(x=>packRank(x.pack)<=rank)}
function save(){localStorage.setItem(K,JSON.stringify(db))}function member(no){return db.members.find(m=>String(m.no)===String(no))}function mn(no){return member(no)?.name||no||'—'}function log(a,e,id,d=''){db.audit.unshift({id:uid('AUD'),date:new Date().toISOString(),action:a,entity:e,id,detail:d});db.audit=db.audit.slice(0,500)}function yrs(){return Object.keys(db.years).sort((a,b)=>+a-+b)}function yof(x){return String(x.year||x.financialYear||String(x.date||'').slice(0,4))}function bal(y){let z=db.years[y]||{opening:0};return(+z.opening||0)+db.transactions.filter(x=>yof(x)===String(y)&&x.kind==='قبض'&&!x.voided).reduce((s,x)=>s+Number(x.amount||0),0)-db.transactions.filter(x=>yof(x)===String(y)&&x.kind==='دفع'&&!x.voided).reduce((s,x)=>s+Number(x.amount||0),0)}
function pg(t,s,b){return'<div class="title"><div><h1>'+t+'</h1><p>'+s+'</p></div></div>'+b}function btn(t,f,c='btn'){return '<button class="'+c+'" onclick="'+f+'">'+t+'</button>'}function sel(id,arr,val=''){return'<select id="'+id+'"><option value="">— اختر —</option>'+arr.map(x=>'<option value="'+esc(x)+'" '+(String(x)===String(val)?'selected':'')+'>'+esc(x)+'</option>').join('')+'</select>'}function fld(l,id,v='',type='text'){return'<div class="field"><label>'+l+'</label><input id="'+id+'" type="'+type+'" value="'+esc(v)+'"></div>'}
function modal(t,b){let e=document.createElement('div');e.className='modalback';e.innerHTML='<div class="modal"><div class="modalhead"><h2>'+t+'</h2><button class="close" onclick="this.closest(\'.modalback\').remove()">×</button></div>'+b+'</div>';document.body.appendChild(e);return e}
function shell(){document.getElementById('app').innerHTML='<header class="top"><div class="brand"><div class="mark">⛰</div><div><b>جمعية الأفق للرياضات الجوية والجبلية</b><small>منصة التسيير المتكاملة — الإصدار 1.0</small></div></div><button class="btn sec" onclick="backup()">نسخة احتياطية</button></header><div class="layout"><nav>'+[['dashboard','⌂ لوحة القيادة'],['members','👥 الأعضاء'],['memberships','🪪 العضويات'],['practitioners','🏃 الممارسون'],['finance','💰 السجل المالي'],['planning','🗓️ التخطيط'],['activities','🏔️ الأنشطة'],['equipment','🧰 المعدات'],['mail','✉️ المراسلات'],['governance','🛡️ الحوكمة'],['documents','📄 الوثائق'],['reports','📊 التقارير'],['settings','⚙️ الإعدادات']].map(x=>'<button data-page="'+x[0]+'">'+x[1]+'</button>').join('')+'</nav><main id="main"></main></div>';document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>go(x.dataset.page));go('dashboard')}
function go(id){document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));let f={dashboard:dashboard,members:membersPage,memberships:membershipsPage,practitioners:practitionersPage,finance:financePage,planning:planningPage,activities:activitiesPage,equipment:equipmentPage,mail:mailPage,governance:govPage,documents:docsPage,reports:reportsPage,settings:settingsPage}[id];document.getElementById('main').innerHTML=f();after(id);scrollTo(0,0)}
function after(id){if(id==='members')renderMembers();if(id==='memberships')renderMemberships();if(id==='practitioners')renderPractitioners();if(id==='finance')renderFinance();if(id==='planning')renderPlanning();if(id==='activities')renderActivities();if(id==='equipment')renderEquipment();if(id==='mail')renderMail();if(id==='governance')renderGov();if(id==='documents')renderDocs();if(id==='reports')renderReports();if(id==='settings')renderSettings();document.getElementById('mq')?.addEventListener('input',renderMembers);['myear','mpack'].forEach(x=>document.getElementById(x)?.addEventListener('change',renderMemberships));document.getElementById('pry')?.addEventListener('change',renderPractitioners);['fy','fk'].forEach(x=>document.getElementById(x)?.addEventListener('change',renderFinance))}
function dashboard(){let y=String(new Date().getFullYear()),t=db.transactions.filter(x=>yof(x)===y&&!x.voided),i=t.filter(x=>x.kind==='قبض').reduce((s,x)=>s+Number(x.amount||0),0),e=t.filter(x=>x.kind==='دفع').reduce((s,x)=>s+Number(x.amount||0),0);return pg('لوحة القيادة','مركز المتابعة للجمعية','<div class="cards"><div class="card"><small>المنخرطون</small><strong>'+db.members.length+'</strong></div><div class="card"><small>العضويات المفعلة '+y+'</small><strong>'+db.memberships.filter(r=>String(r.year)===y&&mstate(r).active).length+'</strong></div><div class="card"><small>القبض '+y+'</small><strong>'+money(i)+'</strong></div><div class="card"><small>الرصيد '+y+'</small><strong>'+money((db.years[y]?.opening||0)+i-e)+'</strong></div></div><div class="panel"><h3>قاعدة المنصة</h3><p class="mut">العضو هو هوية دائمة، والعضوية سجل سنوي مستقل، والحركة المالية تسجل مرة واحدة، والتخطيط منفصل عن التنفيذ.</p></div><div class="panel"><h3>آخر الحركات</h3>'+recent()+'</div>')}
function recent(){let a=db.transactions.filter(x=>!x.voided).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8);return a.length?'<div class="tablebox"><table class="table"><tr><th>التاريخ</th><th>النوع</th><th>البيان</th><th>المبلغ</th></tr>'+a.map(x=>'<tr><td>'+x.date+'</td><td>'+x.kind+'</td><td>'+esc(x.description||x.desc||x.category)+'</td><td>'+money(x.amount)+'</td></tr>').join('')+'</table></div>':'<div class="empty">لا توجد حركات.</div>'}
function membersPage(){return pg('الأعضاء','بطاقة العضو والعضوية السنوية في نقطة عمل واحدة','<div class="notice">هذه القائمة هي نقطة الانطلاق. بيانات العضو تبقى دائمة، وتجديد المعلومات يحدّث البيانات فقط، بينما زر «العضوية» يفتح ملف الاشتراك السنوي. حالة العضوية تُحتسب تلقائيًا وفق شروط الدفع.</div><div class="bar"><input id="mq" placeholder="بحث بالاسم أو الرقم"><button class="btn" onclick="addMember()">+ إضافة عضو</button></div><div id="mt"></div>')}
function memberTableValue(m,col){let y=String(new Date().getFullYear()),r=db.memberships.find(x=>String(x.member)===String(m.no)&&String(x.year)===y),c=r?mstate(r):null;return ({'الرقم':m.no,'الاسم':m.name,'تاريخ الميلاد':m.dob||'—','مكان الميلاد':m.birthPlace||'—','الهاتف':m.phone||'—','البريد الإلكتروني':m.email||'—','الإقامة':m.address||'—','رقم الطوارئ':m.emergencyPhone||'—','الصفة':m.officeRole||m.type||'—','حالة العضوية':c?.membershipStatus||'غير مفعلة'})[col]??'—'}
function renderMembers(){let q=(document.getElementById('mq')?.value||'').toLowerCase(),a=db.members.filter(x=>!q||String(x.name).toLowerCase().includes(q)||String(x.no).includes(q)),cols=(db.settings.memberTableColumns||settingsDefault.memberTableColumns).filter(Boolean),head=cols.map(x=>'<th>'+esc(x)+'</th>').join('');document.getElementById('mt').innerHTML=a.length?'<div class="tablebox"><table class="table"><tr>'+head+'<th>الإجراءات</th></tr>'+a.map(m=>'<tr>'+cols.map(col=>'<td>'+esc(memberTableValue(m,col))+'</td>').join('')+'<td>'+btn('تجديد المعلومات',"editMember('"+m.no+"')",'btn sm')+' '+btn('العضوية',"openMembership('"+m.no+"')",'btn sm sec')+'</td></tr>').join('')+'</table></div>':'<div class="panel empty">لا يوجد أعضاء.</div>'}
function mform(m={}){let ac=Array.isArray(m.activityCodes)?m.activityCodes:[];let activityBox='<div class="field full"><label>الأنشطة المنتمي إليها</label><div class="checkgrid">'+activeActivities().map(a=>'<label class="checkitem"><input type="checkbox" class="mact" value="'+esc(a.code)+'" '+(ac.includes(a.code)?'checked':'')+'> '+esc(a.code)+' — '+esc(a.name)+'</label>').join('')+'</div><small class="mut">اختيار النشاط هنا يحدد الانتماء؛ حق الممارسة يحسب تلقائياً وفق العضوية والباقة.</small></div>';return'<div class="formgrid">'+fld('الاسم واللقب','mn',m.name)+fld('تاريخ الميلاد','md',m.dob,'date')+fld('مكان الميلاد','mb',m.birthPlace)+('<div class="field"><label>الجنس</label>'+sel('mg',['ذكر','أنثى'],m.gender)+'</div>')+fld('الهاتف','mp',m.phone,'tel')+fld('البريد الإلكتروني','me',m.email,'email')+fld('رقم الاتصال عند الطوارئ','mx',m.emergencyPhone,'tel')+fld('مقر الإقامة','ma',m.address)+fld('المهنة','mj',m.occupation)+('<div class="field"><label>الصفة في المكتب</label>'+sel('mr',['الرئيس','نائب الرئيس','الأمين العام','نائب الأمين العام','أمين المال','نائب أمين المال'],m.officeRole)+'</div>')+('<div class="field"><label>نوع المنخرط</label>'+sel('mt',db.settings.membershipTypes,m.type)+'</div>')+fld('تاريخ الانضمام','mi',m.joinDate||today(),'date')+activityBox+'<div class="field full"><label>ملاحظات</label><textarea id="mnotes">'+esc(m.notes||'')+'</textarea></div></div>'}
window.addMember=()=>{window._edit=null;modal('إضافة عضو',mform()+'<div class="actions">'+btn('حفظ',"saveMember()")+'</div>')};window.editMember=n=>{let m=member(n);if(!m)return;window._edit=n;modal('تعديل معلومات العضو','<div class="notice">رقم العضو '+n+' دائم ولا يمكن تغييره.</div>'+mform(m)+'<div class="actions">'+btn('حفظ',"saveMember()")+'</div>')};
window.saveMember=()=>{const g=id=>document.getElementById(id);let v={name:g('mn').value.trim(),dob:g('md').value,birthPlace:g('mb').value.trim(),gender:g('mg').value,phone:g('mp').value.trim(),email:g('me').value.trim(),emergencyPhone:g('mx').value.trim(),address:g('ma').value.trim(),occupation:g('mj').value.trim(),officeRole:g('mr').value,type:g('mt').value,joinDate:g('mi').value,notes:g('mnotes').value.trim(),activityCodes:[...document.querySelectorAll('.mact:checked')].map(x=>x.value)};if(!v.name)return alert('الاسم مطلوب');if(window._edit){Object.assign(member(window._edit),v);log('تعديل','عضو',window._edit,v.name)}else{if(db.members.some(x=>x.name.trim().toLowerCase()===v.name.toLowerCase()&&x.dob===v.dob))return alert('العضو موجود مسبقًا');let ns=db.members.map(x=>+x.no).filter(Number.isFinite);v.no=String((ns.length?Math.max(...ns):0)+1).padStart(4,'0');db.members.push(v);log('إضافة','عضو',v.no,v.name)}save();document.querySelector('.modalback')?.remove();go('members')};
window.viewMember=n=>{let m=member(n);modal('بطاقة العضو','<div class="formgrid">'+[['رقم العضو',m.no],['الاسم',m.name],['تاريخ الميلاد',m.dob],['مكان الميلاد',m.birthPlace],['الجنس',m.gender],['الهاتف',m.phone],['البريد الإلكتروني',m.email],['الطوارئ',m.emergencyPhone],['الإقامة',m.address],['المهنة',m.occupation],['الصفة',m.officeRole],['نوع المنخرط',m.type],['الانضمام',m.joinDate],['الأنشطة', (m.activityCodes||[]).map(code=>{let a=activityByCode(code);return a?a.code+' — '+a.name:'—'}).join('، ') ]].map(x=>'<div class="panel"><small>'+x[0]+'</small><b>'+esc(x[1]||'—')+'</b></div>').join('')+'</div>')}
function semesterForDate(date,year){let d=new Date(String(date||year+'-01-01')+'T12:00:00');if(Number.isNaN(d.getTime()))d=new Date(Number(year),0,1);return d.getMonth()<=5?{key:'S1',label:'السداسي الأول',range:'جانفي–جوان',until:String(year)+'-06-30'}:{key:'S2',label:'السداسي الثاني',range:'جويلية–ديسمبر',until:String(year)+'-12-31'}}
function mstate(r){let p=db.packs[r.pack],tx=db.transactions.filter(x=>x.member===r.member&&x.kind==='قبض'&&x.category==='اشتراكات'&&String(x.membershipYear||x.year)===String(r.year)&&!x.voided).sort((a,b)=>String(a.date).localeCompare(String(b.date))),total=tx.reduce((s,x)=>s+Number(x.amount||0),0),due=Number(r.packValue??p?.v??0),half=due/2,annualActive=!!p&&(r.pack==='A'?total>=due:total>=half),firstHalfTx=tx.find(x=>Number(x.amount||0)===half),firstPayment=firstHalfTx||tx[0],sem=firstPayment?semesterForDate(firstPayment.date,r.year):null,full=total>=due,period=full?'السنة كاملة':(annualActive&&sem?sem.label+' ('+sem.range+')':'—'),practiceUntil=full?String(r.year)+'-12-31':(annualActive&&sem?sem.until:''),practiceActive=r.pack==='A'?false:annualActive&&(!practiceUntil||today()<=practiceUntil),membershipStatus=annualActive?'سارية':'غير مفعلة',practiceStatus=r.pack==='A'?(annualActive?'لا تشمل ممارسة رياضية':'غير مستحقة'):(!annualActive?'غير مستحقة':(full?'السنة كاملة':(practiceActive?'مسموح — '+period:'منتهية — يلزم استكمال 50%')));return{due,total,half,balance:Math.max(0,due-total),credit:Math.max(0,total-due),active:annualActive,membershipStatus,practiceActive,practiceStatus,period,practiceUntil,status:!r.pack?'غير محددة':(full?'مسدد — السنة كاملة':(annualActive?'مسدد جزئيًا — العضوية سارية':'غير مكتمل'))}}
function membershipsPage(){return pg('العضويات المفعلة','تظهر هنا العضويات التي استوفت شروط التفعيل فقط','<div class="bar"><select id="myear">'+yrs().map(y=>'<option>'+y+'</option>').join('')+'</select><select id="mpack"><option value="">كل الباقات</option>'+Object.keys(db.packs).map(k=>'<option value="'+k+'">'+k+' — '+esc(db.packs[k].d)+'</option>').join('')+'</select><button class="btn sec" onclick="printActive()">🖨️ طباعة المفعلة</button></div><div id="mst"></div>')}
function renderMemberships(){let y=document.getElementById('myear')?.value||new Date().getFullYear(),p=document.getElementById('mpack')?.value||'',a=db.memberships.filter(r=>String(r.year)===String(y)&&(!p||r.pack===p)&&mstate(r).membershipStatus==='سارية'),root=document.getElementById('mst');if(!root)return;root.innerHTML=a.length?'<div class="tablebox"><table class="table"><tr><th>السنة</th><th>العضو</th><th>الباقة</th><th>المستحق</th><th>المدفوع</th><th>المتبقي</th><th>حالة العضوية</th><th>حق المزاولة</th><th>فترة المزاولة</th></tr>'+a.map(r=>{let c=mstate(r);return'<tr><td>'+esc(r.year)+'</td><td>'+esc(mn(r.member))+'</td><td>'+esc(r.pack)+'</td><td>'+money(c.due)+'</td><td>'+money(c.total)+'</td><td>'+(c.balance?money(c.balance):'\\')+'</td><td>سارية</td><td><span class="badge '+(c.practiceActive?'':'warn')+'">'+esc(c.practiceStatus)+'</span></td><td>'+esc(c.period)+'</td></tr>'}).join('')+'</table></div>':'<div class="panel empty">لا توجد عضويات مفعلة لهذه السنة.</div>'}
window.openMembershipById=id=>{let r=db.memberships.find(x=>String(x.id)===String(id));if(!r)return alert('العضوية غير موجودة');window.openMembership(String(r.member),String(r.year))};
window.openMembership=(no='',y='')=>{y=y||document.getElementById('myear')?.value||String(new Date().getFullYear());let r=db.memberships.find(x=>String(x.member)===String(no)&&String(x.year)===String(y))||{member:no,year:+y,pack:''},c=r.pack?mstate(r):{due:0,total:0,balance:0,membershipStatus:'غير مفعلة',practiceStatus:'غير مستحقة',period:'—'},prev=db.memberships.filter(x=>String(x.member)===String(no)&&String(x.year)<String(y)).sort((a,b)=>+b.year-+a.year)[0],pc=prev?mstate(prev):null,membersOpt=db.members.map(m=>m.no+' — '+m.name);modal('ملف العضوية السنوية','<div class="notice"><b>العضو:</b> '+esc(mn(no))+' — <b>السنة:</b> '+esc(y)+'</div>'+(prev?'<div class="panel"><h3>ملخص العضوية السابقة ('+esc(prev.year)+')</h3><p>الباقة: <b>'+esc(prev.pack)+'</b> — المدفوع: <b>'+money(pc.total)+'</b> — المتبقي: <b>'+(pc.balance?money(pc.balance):'\\')+'</b> — الحالة: <b>'+esc(pc.membershipStatus)+'</b></p></div>':'<div class="notice">لا توجد عضوية سابقة مسجلة لهذا العضو.</div>')+'<div class="formgrid"><div class="field"><label>العضو</label>'+sel('mm',membersOpt,no?no+' — '+mn(no):'')+'</div>'+sel('my',yrs(),String(y))+'<div class="field"><label>الباقة</label>'+sel('mk',Object.keys(db.packs).map(k=>k+' — '+db.packs[k].d),r.pack?r.pack+' — '+db.packs[r.pack].d:'')+'</div>'+fld('قيمة الباقة','mplan',c.due?money(c.due):'')+moneyInput('mpay')+'<div class="field"><label>طريقة الدفع</label>'+sel('mpm',db.settings.paymentMethods)+'</div>'+fld('تاريخ الدفع','mpd',today(),'date')+fld('إجمالي المدفوع سابقًا','mpaid',money(c.total))+fld('المتبقي','mbal',c.balance?money(c.balance):'\\')+fld('حالة العضوية','mstat',c.membershipStatus)+'<div class="field"><label>حق مزاولة النشاط</label><input id="mpractice" type="text" value="'+esc(c.practiceStatus)+'" readonly></div><div class="field full"><label>فترة المزاولة</label><input id="mperiod" type="text" value="'+esc(c.period==='—'?'':c.period)+'" readonly></div></div><div id="mrule" class="notice">اختر الباقة لمعرفة شروط التفعيل.</div><div class="actions">'+btn('حفظ وتفعيل تلقائيًا',"saveMembership()")+'</div>');setTimeout(()=>{document.getElementById('mm')?.addEventListener('change',refreshMC);document.getElementById('mk')?.addEventListener('change',refreshMC);document.getElementById('my')?.addEventListener('change',refreshMC);document.getElementById('mpay')?.addEventListener('input',refreshMC);bindMoneyInput('mpay');refreshMC()},0)};
window.refreshMC=()=>{const g=id=>document.getElementById(id),n=(g('mm')?.value||'').split(' — ')[0],p=(g('mk')?.value||'').split(' — ')[0],y=g('my')?.value||'',r=db.memberships.find(x=>x.member===n&&String(x.year)===String(y))||{member:n,pack:p,year:y,period:''},pack=db.packs[p],c=pack?mstate({...r,pack:p}):{due:0,total:0,half:0,balance:0,status:'غير محددة',active:false,period:'—'};if(g('mplan'))g('mplan').value=pack?money(pack.v):'';if(g('mpaid'))g('mpaid').value=money(c.total);if(g('mbal'))g('mbal').value=c.balance?money(c.balance):'\\';if(g('mstat'))g('mstat').value=c.membershipStatus;if(g('mpractice'))g('mpractice').value=c.practiceStatus;if(g('mperiod'))g('mperiod').value=c.period==='—'?'':c.period;let rule=pack?(p==='A'?'الباقة A: يجب دفع 100% فقط — '+money(pack.v):'الباقة '+p+': المسموح في كل عملية هو 50% ('+money(pack.v/2)+') أو 100% ('+money(pack.v)+'). عند دفع 50% تبقى العضوية سارية للسنة كاملة، بينما حق المزاولة يكون لسداسي واحد فقط.'): 'اختر الباقة';if(g('mrule'))g('mrule').textContent=rule;let pay=parseMoney(g('mpay')?.value||0);if(g('mpay')&&pack&&!pay)g('mpay').placeholder=p==='A'?String(pack.v):String(pack.v/2)};
window.saveMembership=()=>{const g=id=>document.getElementById(id),n=(g('mm')?.value||'').split(' — ')[0],p=(g('mk')?.value||'').split(' — ')[0],y=String(g('my')?.value||'');if(!n||!p)return alert('اختر العضو والباقة');let pack=db.packs[p];if(!pack)return alert('الباقة غير موجودة');if(db.years[y]?.status==='closed')return alert('السنة '+y+' مغلقة');let amount=parseMoney(g('mpay')?.value||0),half=Number(pack.v||0)/2,full=Number(pack.v||0),valid=p==='A'?amount===full:(amount===half||amount===full);if(!valid)return alert(p==='A'?'مرفوض: الباقة A تتطلب دفع 100% فقط ('+money(full)+').':'مرفوض: يجب أن يكون المدفوع 50% أو 100% من قيمة الباقة. المبالغ المقبولة: '+money(half)+' أو '+money(full)+'.');let r=db.memberships.find(x=>x.member===n&&String(x.year)===y);if(!r){r={id:uid('MS'),member:n,year:+y,pack:p,packValue:full,createdAt:today(),period:''};db.memberships.push(r)}else{if(r.pack!==p)return alert('لا يمكن تغيير الباقة بعد تسجيل حركات مالية عليها.');r.pack=p;if(r.packValue==null)r.packValue=full}let existing=db.transactions.filter(x=>x.member===n&&x.kind==='قبض'&&x.category==='اشتراكات'&&String(x.membershipYear||x.year)===y&&!x.voided).reduce((a,x)=>a+Number(x.amount||0),0);if(existing+amount>full)return alert('مرفوض: المبلغ سيجعل المدفوع يتجاوز قيمة الباقة.');let period=amount===full?'السنة كاملة':((new Date((g('mpd')?.value||today())+'T00:00:00').getMonth()+1)<=6?'النصف الأول':'النصف الثاني');if(p!=='A'&&amount===half)r.period=period;else if(amount===full)r.period='السنة كاملة';r.updatedAt=today();let seq=db.transactions.map(x=>Number(x.number)||0).filter(Number.isFinite),num=(seq.length?Math.max(...seq):0)+1;let tx={id:uid('OP'),number:num,date:g('mpd')?.value||today(),year:y,financialYear:y,kind:'قبض',amount,member:n,category:'اشتراكات',account:g('mpm')?.value||'نقدًا',method:g('mpm')?.value||'نقدًا',ref:'اشتراك-'+y+'-'+String(num).padStart(4,'0'),description:'اشتراك سنوي — باقة '+p+' — '+(amount===full?'100%':'50%'),membershipYear:y,membershipId:r.id};db.transactions.push(tx);log('إضافة','حركة مالية',tx.id,'اشتراك '+p+' للعضو '+mn(n)+' — '+money(amount));log('تفعيل','عضوية',r.id,mn(n)+' — '+(amount===full?'السنة كاملة':period));save();document.querySelector('.modalback')?.remove();go('memberships')};window.printActive=()=>{let y=document.getElementById('myear').value,a=db.memberships.filter(r=>String(r.year)===y&&mstate(r).active).map(r=>member(r.member)).filter(Boolean),w=open('','_blank');if(!w)return;w.document.write('<html dir="rtl"><meta charset="utf-8"><style>body{font-family:Arial;padding:25px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #555;padding:8px}</style><h2>جمعية الأفق للرياضات الجوية والجبلية</h2><h3>قائمة الأعضاء المفعلة لسنة '+y+'</h3><table><tr><th>م</th><th>الرقم</th><th>الاسم</th><th>النوع</th></tr>'+a.map((m,i)=>'<tr><td>'+(i+1)+'</td><td>'+m.no+'</td><td>'+esc(m.name)+'</td><td>'+esc(m.type||'—')+'</td></tr>').join('')+'</table></html>');w.document.close();setTimeout(()=>w.print(),100)};

// ===== practitioners =====
function practitionersPage(){return pg('الممارسون','قائمة مشتقة من الأعضاء والعضويات — لا تُنشأ فيها هوية العضو من جديد','<div class="bar"><select id="pry">'+yrs().map(y=>'<option>'+y+'</option>').join('')+'</select><button class="btn sec" onclick="printPractitioners()">🖨️ طباعة القائمة</button></div><div class="notice">A تفعّل العضوية والحقوق الإدارية فقط. الباقات B–F تمنح حق ممارسة نشاطها والأنشطة الأدنى ترتيباً، وفق العضوية السارية وفترة الممارسة.</div><div id="prt"></div>')}
function renderPractitioners(){let y=document.getElementById('pry')?.value||String(new Date().getFullYear()),rows=[];db.members.forEach(m=>{let r=db.memberships.find(x=>String(x.member)===String(m.no)&&String(x.year)===String(y)),c=r?mstate(r):null;if(!r||!c?.active||r.pack==='A')return;let assigned=Array.isArray(m.activityCodes)?m.activityCodes:[];let allowed=eligibleActivities(r.pack).filter(a=>assigned.length?assigned.includes(a.code):true);allowed.forEach(a=>rows.push({m,r,c,a,ps:practiceLabel(m,r,c,a)}))});let root=document.getElementById('prt');if(!root)return;rows.sort((x,y)=>{let ao=x.a.order||0,bo=y.a.order||0;return ao-bo||String(x.m.name).localeCompare(String(y.m.name),'ar')});root.innerHTML=rows.length?'<div class="tablebox"><table class="table"><tr><th>الرمز</th><th>الممارس</th><th>النشاط</th><th>الباقة المدفوعة</th><th>حق الممارسة</th><th>الفترة</th><th>إجراء</th></tr>'+rows.map(x=>'<tr><td><b>'+esc(x.a.code)+'</b></td><td>'+esc(x.m.name)+'</td><td>'+esc(x.a.name)+'</td><td>'+esc(x.r.pack)+'</td><td><span class="badge '+(x.c.practiceActive?'':'warn')+'">'+esc(x.c.practiceStatus)+'</span></td><td>'+esc(x.c.period)+'</td></tr>').join('')+'</table></div>':'<div class="panel empty">لا توجد سجلات ممارسة مستحقة لهذه السنة.</div>'}
window.toggleFreeze=(no,code)=>{let m=member(no);if(!m)return;m.practiceFreeze=m.practiceFreeze||{};m.practiceFreeze[code]=!m.practiceFreeze[code];log(m.practiceFreeze[code]?'تجميد ممارسة':'رفع تجميد ممارسة','ممارس',no,'النشاط '+code);save();renderPractitioners()};window.printPractitioners=()=>{let y=document.getElementById('pry')?.value||String(new Date().getFullYear()),root=document.getElementById('prt');let w=open('','_blank');if(!w||!root)return;w.document.write('<html dir="rtl"><meta charset="utf-8"><style>body{font-family:Arial;padding:20px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #555;padding:7px}</style><h2>جمعية الأفق — قائمة الممارسين '+y+'</h2>'+root.innerHTML+'</html>');w.document.close();setTimeout(()=>w.print(),100)};
// ===== finance =====
function financePage(){return pg('السجل المالي الموحد','قبض ودفع في سجل محاسبي واحد','<div class="bar"><select id="fy"><option value="">كل السنوات</option>'+yrs().map(y=>'<option>'+y+'</option>').join('')+'</select><select id="fk"><option value="">كل الحركات</option><option>قبض</option><option>دفع</option></select><button class="btn" onclick="addTx()">+ تسجيل حركة</button><button class="btn sec" onclick="printJournal()">🖨️ طباعة</button></div><div id="ft"></div>')}
function renderFinance(){let y=document.getElementById('fy')?.value||'',k=document.getElementById('fk')?.value||'',a=db.transactions.filter(x=>(!y||yof(x)===y)&&(!k||x.kind===k)).sort((a,b)=>String(b.date).localeCompare(String(a.date))),i=a.filter(x=>x.kind==='قبض').reduce((s,x)=>s+Number(x.amount||0),0),e=a.filter(x=>x.kind==='دفع').reduce((s,x)=>s+Number(x.amount||0),0);document.getElementById('ft').innerHTML='<div class="cards"><div class="card"><small>القبض</small><strong>'+money(i)+'</strong></div><div class="card"><small>الدفع</small><strong>'+money(e)+'</strong></div><div class="card"><small>الصافي</small><strong>'+money(i-e)+'</strong></div></div><div class="tablebox" style="margin-top:12px"><table class="table"><tr><th>رقم</th><th>التاريخ</th><th>السنة</th><th>النوع</th><th>البيان</th><th>العضو</th><th>الفئة</th><th>الحساب</th><th>المبلغ</th><th></th></tr>'+a.map(x=>'<tr><td>'+esc(x.number||'—')+'</td><td>'+x.date+'</td><td>'+yof(x)+'</td><td>'+x.kind+'</td><td>'+esc(x.description||x.desc||'')+'</td><td>'+esc(mn(x.member))+'</td><td>'+esc(x.category||'')+'</td><td>'+esc(x.account||'')+'</td><td>'+money(x.amount)+'</td><td>'+btn('إلغاء',"voidTx('"+x.id+"')",'btn sm bad')+'</td></tr>').join('')+'</table></div>'}
window.addTx=()=>{let opts=db.members.map(m=>m.no+' — '+m.name);modal('تسجيل حركة مالية','<div class="formgrid">'+fld('التاريخ','txd',today(),'date')+'<div class="field"><label>النوع</label>'+sel('txk',['قبض','دفع'])+'</div>'+moneyInput('txa')+'<div class="field"><label>السنة المالية</label>'+sel('txy',yrs(),String(new Date().getFullYear()))+'</div><div class="field"><label>العضو</label>'+sel('txm',opts)+'</div><div class="field"><label>الفئة</label>'+sel('txc',['اشتراكات','تكوين','مداخيل أنشطة','دعم/إعانة','تبرع','نقل','معدات','صيانة','إدارة','اتصالات','مصاريف بنكية','أخرى'])+'</div><div class="field"><label>الحساب</label>'+sel('txacc',db.settings.accounts)+'</div>'+fld('رقم المرجع','txref')+'<div class="field full"><label>البيان</label><textarea id="txdsc"></textarea></div></div><div class="notice">السنة المغلقة محمية من الحركات الجديدة.</div><div class="actions">'+btn('حفظ',"saveTx()")+'</div>')}
window.saveTx=()=>{let y=String(txy.value);if(db.years[y]?.status==='closed')return alert('السنة '+y+' مغلقة');let amount=parseMoney(txa.value);if(!amount)return alert('أدخل المبلغ');let n=(txm.value||'').split(' — ')[0],x={id:uid('OP'),date:txd.value,year:y,financialYear:y,kind:txk.value,amount,member:n,category:txc.value,account:txacc.value,ref:txref.value,description:txdsc.value.trim()};if(x.category==='اشتراكات'&&n){x.membershipYear=y;x.membershipId=db.memberships.find(r=>r.member===n&&String(r.year)===y)?.id||''}db.transactions.push(x);log('إضافة','حركة مالية',x.id,x.description);save();document.querySelector('.modalback')?.remove();go('finance')};
window.voidTx=id=>{let x=db.transactions.find(q=>q.id===id);if(!x)return;if(db.years[yof(x)]?.status==='closed')return alert('السنة مغلقة');if(confirm('إلغاء الحركة دون حذفها؟')){x.voided=true;log('إلغاء','حركة مالية',id,x.description);save();go('finance')}};
window.printJournal=()=>{let w=open('','_blank');if(!w)return;let a=db.transactions.filter(x=>!x.voided);w.document.write('<html dir="rtl"><meta charset="utf-8"><style>body{font-family:Arial;padding:20px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #555;padding:7px}</style><h2>السجل المحاسبي — جمعية الأفق</h2><table><tr><th>م</th><th>التاريخ</th><th>النوع</th><th>البيان</th><th>العضو</th><th>المبلغ</th></tr>'+a.map((x,i)=>'<tr><td>'+esc(x.number||i+1)+'</td><td>'+x.date+'</td><td>'+x.kind+'</td><td>'+esc(x.description)+'</td><td>'+esc(mn(x.member))+'</td><td>'+money(x.amount)+'</td></tr>').join('')+'</table></html>');w.document.close();setTimeout(()=>w.print(),100)};

// ===== planning & activities =====
function planningPage(){return pg('التخطيط السنوي','التخطيط يحدد النشاط والتكلفة التقديرية قبل التنفيذ','<div class="bar"><select id="py">'+yrs().map(y=>'<option>'+y+'</option>').join('')+'</select><button class="btn" onclick="addPlan()">+ إضافة بند مخطط</button></div><div id="pt"></div>')}
function renderPlanning(){let y=document.getElementById('py')?.value||new Date().getFullYear(),a=db.plans.filter(x=>String(x.year)===String(y));document.getElementById('pt').innerHTML=a.length?'<div class="tablebox"><table class="table"><tr><th>العنوان</th><th>المحور</th><th>الفترة</th><th>التكلفة التقديرية</th><th>المسؤول</th><th>الحالة</th></tr>'+a.map(x=>'<tr><td>'+esc(x.title)+'</td><td>'+esc(x.axis)+'</td><td>'+esc(x.period)+'</td><td>'+money(x.estimated||0)+'</td><td>'+esc(mn(x.owner))+'</td><td>'+esc(x.status||'مبرمج')+'</td></tr>').join('')+'</table></div>':'<div class="panel empty">لا توجد بنود.</div>'}
window.addPlan=()=>{modal('إضافة بند تخطيط','<div class="formgrid">'+fld('العنوان','ptitle')+fld('المحور','paxis')+fld('الفترة','pperiod')+moneyInput('pcost')+'<div class="field"><label>المسؤول</label>'+sel('powner',db.members.map(m=>m.no+' — '+m.name))+'</div><div class="field"><label>السنة</label>'+sel('pyear',yrs(),String(new Date().getFullYear()))+'</div><div class="field full"><label>ملاحظات</label><textarea id="pnotes"></textarea></div></div><div class="actions">'+btn('حفظ',"savePlan()")+'</div>')}
window.savePlan=()=>{let x={id:uid('PL'),title:ptitle.value,axis:paxis.value,period:pperiod.value,estimated:parseMoney(pcost.value||0),owner:(powner.value||'').split(' — ')[0],year:pyear.value,notes:pnotes.value,status:'مبرمج'};db.plans.push(x);log('إضافة','تخطيط',x.id,x.title);save();document.querySelector('.modalback')?.remove();go('planning')};
function activitiesPage(){return pg('الأنشطة','سجل التنفيذ الفعلي وربطه بالمشاركين والمالية','<div class="bar"><select id="ay">'+yrs().map(y=>'<option>'+y+'</option>').join('')+'</select><button class="btn" onclick="addActivity()">+ تسجيل نشاط</button></div><div id="at"></div>')}
function renderActivities(){let y=document.getElementById('ay')?.value||new Date().getFullYear(),a=db.activities.filter(x=>String(x.year||String(x.date||'').slice(0,4))===String(y));document.getElementById('at').innerHTML=a.length?'<div class="tablebox"><table class="table"><tr><th>التاريخ</th><th>النشاط</th><th>النوع</th><th>المكان</th><th>المسؤول</th><th>الحالة</th><th></th></tr>'+a.map(x=>'<tr><td>'+esc(x.date)+'</td><td><b>'+esc(x.title||x.name)+'</b></td><td>'+esc(x.type)+'</td><td>'+esc(x.place)+'</td><td>'+esc(mn(x.responsible))+'</td><td>'+esc(x.status)+'</td><td>'+btn('فتح',"viewActivity('"+x.id+"')",'btn sm')+'</td></tr>').join('')+'</table></div>':'<div class="panel empty">لا توجد أنشطة.</div>'}
window.addActivity=()=>modal('تسجيل نشاط','<div class="formgrid">'+fld('العنوان','an')+fld('التاريخ','ad',today(),'date')+'<div class="field"><label>النوع</label>'+sel('aty',db.settings.activityTypes)+'</div>'+fld('المكان','apl')+'<div class="field"><label>المسؤول</label>'+sel('aown',db.members.map(m=>m.no+' — '+m.name))+'</div><div class="field"><label>الحالة</label>'+sel('ast',db.settings.statuses)+'</div>'+moneyInput('aec')+'<div class="field full"><label>ملاحظات</label><textarea id="ano"></textarea></div></div><div class="actions">'+btn('حفظ',"saveActivity()")+'</div>');
window.saveActivity=()=>{let x={id:uid('ACT'),title:an.value,date:ad.value,year:ad.value.slice(0,4),type:aty.value,place:apl.value,responsible:(aown.value||'').split(' — ')[0],status:ast.value,estimated:parseMoney(aec.value||0),notes:ano.value};db.activities.push(x);log('إضافة','نشاط',x.id,x.title);save();document.querySelector('.modalback')?.remove();go('activities')};
window.viewActivity=id=>{let a=db.activities.find(x=>x.id===id);if(!a)return;let ps=db.participants.filter(x=>x.activity===id);modal('ملف النشاط','<div class="panel"><h3>'+esc(a.title)+'</h3><p>'+esc(a.date)+' — '+esc(a.type)+' — '+esc(a.place)+'</p><p>المسؤول: '+esc(mn(a.responsible))+' — الحالة: '+esc(a.status)+'</p></div><div class="panel"><h3>المشاركون ('+ps.length+')</h3>'+ps.map(x=>'<p>'+esc(mn(x.member))+' — '+esc(x.role||'مشارك')+'</p>').join('')+btn('+ إضافة مشارك',"addParticipant('"+id+"')",'btn sm')+'</div>')}
window.addParticipant=id=>{modal('إضافة مشارك','<div class="field"><label>العضو</label>'+sel('pm',db.members.map(m=>m.no+' — '+m.name))+'</div><div class="field"><label>الدور</label>'+sel('pr',db.settings.roles)+'</div><div class="actions">'+btn('حفظ',"saveParticipant('"+id+"')")+'</div>')};window.saveParticipant=id=>{let n=(pm.value||'').split(' — ')[0];if(!n)return;db.participants.push({id:uid('PART'),activity:id,member:n,role:pr.value,date:today()});save();document.querySelector('.modalback')?.remove();viewActivity(id)};

// ===== equipment =====
function equipmentPage(){return pg('المعدات','اقتناء، حالة، إعارة وصيانة المعدات','<div class="bar"><button class="btn" onclick="addEquipment()">+ تسجيل معدة</button></div><div id="eqt"></div>')}
function renderEquipment(){let a=db.equipment;document.getElementById('eqt').innerHTML=a.length?'<div class="tablebox"><table class="table"><tr><th>الاسم</th><th>الرمز</th><th>التخصص</th><th>المصدر</th><th>الحالة</th><th>تاريخ الاقتناء</th></tr>'+a.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.code)+'</td><td>'+esc(x.specialty)+'</td><td>'+esc(x.source)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.date)+'</td></tr>').join('')+'</table></div>':'<div class="panel empty">لا توجد معدات.</div>'}
window.addEquipment=()=>modal('تسجيل معدة','<div class="formgrid">'+fld('اسم المعدة','en')+fld('الرمز','ec')+fld('التخصص','es')+fld('المصدر','eso')+fld('تاريخ الاقتناء','ed',today(),'date')+'<div class="field"><label>الحالة</label>'+sel('est',['جيدة','تحتاج صيانة','معطلة','مستعملة'])+'</div><div class="field full"><label>ملاحظات</label><textarea id="enotes"></textarea></div></div><div class="actions">'+btn('حفظ',"saveEquipment()")+'</div>');window.saveEquipment=()=>{db.equipment.push({id:uid('EQ'),name:en.value,code:ec.value,specialty:es.value,source:eso.value,date:ed.value,status:est.value,notes:enotes.value});save();document.querySelector('.modalback')?.remove();go('equipment')};

// ===== mail =====
function mailPage(){return pg('المراسلات','وارد وصادر ومراسلات إدارية كسجلات مستقلة','<div class="tabs">'+btn('+ وارد',"addMail('in')",'btn')+btn('+ صادر',"addMail('out')",'btn')+btn('+ مراسلة إدارية',"addMail('corr')",'btn')+'</div><div class="cards"><div class="card"><small>الوارد</small><strong>'+db.incoming.length+'</strong></div><div class="card"><small>الصادر</small><strong>'+db.outgoing.length+'</strong></div><div class="card"><small>المراسلات</small><strong>'+db.correspondence.length+'</strong></div></div><div id="mailt" style="margin-top:12px"></div>')}
function renderMail(){let all=[...db.incoming.map(x=>({...x,kind:'وارد'})),...db.outgoing.map(x=>({...x,kind:'صادر'})),...db.correspondence.map(x=>({...x,kind:'مراسلة'}))].sort((a,b)=>String(b.date).localeCompare(String(a.date)));document.getElementById('mailt').innerHTML='<div class="tablebox"><table class="table"><tr><th>النوع</th><th>المرجع</th><th>التاريخ</th><th>الجهة</th><th>الموضوع</th><th>الحالة</th></tr>'+all.map(x=>'<tr><td>'+x.kind+'</td><td>'+esc(x.ref)+'</td><td>'+esc(x.date)+'</td><td>'+esc(x.party||x.from||x.to)+'</td><td>'+esc(x.subject)+'</td><td>'+esc(x.status)+'</td></tr>').join('')+'</table></div>'}
window.addMail=k=>modal(k==='in'?'بريد وارد':k==='out'?'بريد صادر':'مراسلة إدارية','<div class="formgrid">'+fld('المرجع','mr')+fld('التاريخ','mdate',today(),'date')+fld('الجهة','mparty')+fld('الموضوع','msub')+fld('النوع','mtype')+fld('الحالة','mstatus','جديدة')+'<div class="field full"><label>ملاحظات</label><textarea id="mnote"></textarea></div></div><div class="actions">'+btn('حفظ',"saveMail('"+k+"')")+'</div>');
window.saveMail=k=>{let x={id:uid(k.toUpperCase()),ref:mr.value,date:mdate.value,party:mparty.value,subject:msub.value,type:mtype.value,status:mstatus.value,notes:mnote.value};db[k==='in'?'incoming':k==='out'?'outgoing':'correspondence'].push(x);log('إضافة','مراسلة',x.id,x.subject);save();document.querySelector('.modalback')?.remove();go('mail')};

// ===== governance =====
function govPage(){return pg('الحوكمة والمتابعة','اجتماعات وقرارات ومهام','<div class="tabs">'+btn('+ اجتماع',"addGov('meeting')")+btn('+ قرار',"addGov('decision')")+btn('+ مهمة',"addGov('task')")+'</div><div id="govt"></div>')}
function renderGov(){document.getElementById('govt').innerHTML=['meeting','decision','task'].map((k,i)=>{let arr=k==='meeting'?db.meetings:k==='decision'?db.decisions:db.tasks;return '<div class="panel"><h3>'+['الاجتماعات','القرارات','المهام'][i]+'</h3>'+arr.map(x=>'<p><b>'+esc(x.title)+'</b> — '+esc(x.date||x.due||'')+' — '+esc(x.owner||'')+'</p>').join('')+'</div>'}).join('')}
window.addGov=k=>modal(k==='meeting'?'إضافة اجتماع':k==='decision'?'إضافة قرار':'إضافة مهمة','<div class="formgrid">'+fld('العنوان','gt')+fld('التاريخ/الأجل','gd',today(),'date')+'<div class="field"><label>المسؤول</label>'+sel('go',db.members.map(m=>m.no+' — '+m.name))+'</div><div class="field full"><label>التفاصيل</label><textarea id="gtext"></textarea></div></div><div class="actions">'+btn('حفظ',"saveGov('"+k+"')")+'</div>');window.saveGov=k=>{let x={id:uid(k),title:gt.value,date:gd.value,owner:(go.value||'').split(' — ')[0],text:gtext.value,status:'مفتوح'};db[k==='meeting'?'meetings':k==='decision'?'decisions':'tasks'].push(x);save();document.querySelector('.modalback')?.remove();go('governance')};

// ===== documents =====
function docsPage(){return pg('الوثائق','فهرس الوثائق وربطها بالأنشطة','<div class="bar"><button class="btn" onclick="addDoc()">+ إضافة وثيقة</button></div><div id="doct"></div>')}
function renderDocs(){document.getElementById('doct').innerHTML=db.documents.length?'<div class="tablebox"><table class="table"><tr><th>الرقم</th><th>التاريخ</th><th>النوع</th><th>العنوان</th><th>النشاط المرتبط</th></tr>'+db.documents.map(x=>'<tr><td>'+esc(x.number)+'</td><td>'+esc(x.date)+'</td><td>'+esc(x.type)+'</td><td>'+esc(x.title)+'</td><td>'+esc(db.activities.find(a=>a.id===x.activity)?.title||'—')+'</td></tr>').join('')+'</table></div>':'<div class="panel empty">لا توجد وثائق.</div>'}
window.addDoc=()=>modal('إضافة وثيقة','<div class="formgrid">'+fld('رقم الوثيقة','dn')+fld('التاريخ','dd',today(),'date')+fld('النوع','dt')+fld('العنوان','dtitle')+'<div class="field"><label>النشاط</label>'+sel('da',db.activities.map(x=>x.id+' — '+(x.title||x.name)))+'</div><div class="field full"><label>ملاحظات</label><textarea id="dnote"></textarea></div></div><div class="actions">'+btn('حفظ',"saveDoc()")+'</div>');window.saveDoc=()=>{db.documents.push({id:uid('DOC'),number:dn.value,date:dd.value,type:dt.value,title:dtitle.value,activity:(da.value||'').split(' — ')[0],notes:dnote.value});save();document.querySelector('.modalback')?.remove();go('documents')};

// ===== reports =====
function reportsPage(){return pg('التقارير والمؤشرات','قراءة موحدة للبيانات','<div class="bar"><select id="ry">'+yrs().map(y=>'<option>'+y+'</option>').join('')+'</select><button class="btn sec" onclick="printReport()">🖨️ التقرير السنوي</button></div><div id="rt"></div>')}
function renderReports(){let y=document.getElementById('ry')?.value||new Date().getFullYear(),t=db.transactions.filter(x=>yof(x)===String(y)&&!x.voided),i=t.filter(x=>x.kind==='قبض').reduce((s,x)=>s+Number(x.amount||0),0),e=t.filter(x=>x.kind==='دفع').reduce((s,x)=>s+Number(x.amount||0),0),a=db.activities.filter(x=>String(x.year||String(x.date||'').slice(0,4))===String(y)),p=db.plans.filter(x=>String(x.year)===String(y));document.getElementById('rt').innerHTML='<div class="cards"><div class="card"><small>الأعضاء</small><strong>'+db.members.length+'</strong></div><div class="card"><small>التخطيط</small><strong>'+p.length+'</strong></div><div class="card"><small>الأنشطة</small><strong>'+a.length+'</strong></div><div class="card"><small>القبض</small><strong>'+money(i)+'</strong></div><div class="card"><small>الدفع</small><strong>'+money(e)+'</strong></div><div class="card"><small>الرصيد</small><strong>'+money((db.years[y]?.opening||0)+i-e)+'</strong></div></div>'}
window.printReport=()=>{let y=document.getElementById('ry').value,w=open('','_blank');if(!w)return;w.document.write('<html dir="rtl"><meta charset="utf-8"><style>body{font-family:Arial;padding:25px}</style><h1>التقرير السنوي — جمعية الأفق — '+y+'</h1>'+document.getElementById('rt').innerHTML+'</html>');w.document.close();setTimeout(()=>w.print(),100)};

// ===== settings =====
function settingsPage(){return pg('الإعدادات','إدارة القواميس والأنشطة والباقات والسنوات — مع مراعاة أن اعتماد الرسوم والتكاليف يجب أن يستند إلى النظام الأساسي وقرارات الجمعية والنصوص التنظيمية المختصة.','<div class="panel"><h3>أعمدة جدول الأعضاء</h3><p class="mut">حدد المعلومات التي تظهر في قائمة الأعضاء. الترتيب أدناه هو ترتيب العرض.</p><div id="membercols"></div></div><div class="panel"><h3>الأنشطة وباقات الممارسة</h3><p class="mut">B–F هي مستويات ممارسة قابلة للإدارة. A هو الاشتراك السنوي القانوني ولا يمنح حق ممارسة رياضية.</p><div id="activitycfg"></div><div class="actions">'+btn('+ إضافة نشاط',"addActivityConfig()")+'</div></div><div class="panel"><h3>الباقة A — الاشتراك السنوي القانوني</h3><div id="packA"></div></div><div class="panel"><h3>القواميس العامة</h3><div class="bar"><select id="sk">'+Object.keys(db.settings).filter(k=>Array.isArray(db.settings[k])&&k!=='memberTableColumns').map(k=>'<option>'+k+'</option>').join('')+'</select><input id="sv" placeholder="عنصر جديد"><button class="btn" onclick="addSetting()">+ إضافة</button></div><div id="st"></div></div><div class="panel"><h3>السنوات المالية</h3><div id="years"></div></div><div class="panel"><h3>ضوابط الحوكمة</h3><p class="mut">المنصة تحفظ السجل المالي كسجل موحد، تمنع الحذف المباشر للحركات وتستخدم الإلغاء، وتحمي السنوات المغلقة. أي رسم أو تكلفة أو حق ممارسة يجب أن يوافق الإطار القانوني والتنظيمي المعتمد للجمعية.</p></div>')}
function renderSettings(){let k=document.getElementById('sk')?.value||Object.keys(db.settings).filter(k=>Array.isArray(db.settings[k])&&k!=='memberTableColumns')[0],cols=db.settings.memberTableColumns||settingsDefault.memberTableColumns;document.getElementById('membercols').innerHTML=cols.map((x,i)=>'<div class="panel"><label class="checkitem"><input type="checkbox" checked onchange="toggleMemberColumn('+i+',this.checked)"> '+esc(x)+'</label></div>').join('');document.getElementById('activitycfg').innerHTML=activeActivities().map(a=>{let p=db.packs[a.pack]||{};return '<div class="panel"><div class="row"><b>'+esc(a.code)+' — '+esc(a.name)+'</b><span class="mut">الباقة '+esc(a.pack)+' — '+money(p.v||0)+'</span></div>'+btn('تعديل',"editActivityConfig('"+a.code+"')",'btn sm')+' '+btn('الباقة',"editActivityPack('"+a.pack+"')",'btn sm sec')+' '+btn('تعطيل',"toggleActivityConfig('"+a.code+"')",'btn sm bad')+'</div>'}).join('')||'<div class="empty">لا توجد أنشطة.</div>';let A=db.packs.A||packsDefault.A;document.getElementById('packA').innerHTML='<div class="formgrid">'+fld('تسمية الاشتراك','paDesc',A.d)+moneyInput('paValue',A.v)+'</div><div class="actions">'+btn('حفظ A',"savePackA()")+'</div>';document.getElementById('st').innerHTML=(db.settings[k]||[]).map((x,i)=>'<div class="panel"><span>'+esc(x)+'</span> '+btn('حذف',"removeSetting('"+k+"',"+i+")",'btn sm bad')+'</div>').join('');document.getElementById('years').innerHTML=yrs().map(y=>'<div class="panel"><b>'+y+'</b> — '+(db.years[y].status==='closed'?'مغلقة':'مفتوحة')+' — افتتاحي '+money(db.years[y].opening||0)+' — رصيد '+money(bal(y))+(db.years[y].status==='open'?btn('إغلاق',"closeYear('"+y+"')",'btn sm sec'):'')+'</div>').join('');bindMoneyInput('paValue')}
window.toggleMemberColumn=(i,on)=>{let cols=db.settings.memberTableColumns||[];if(on){if(!cols.includes(settingsDefault.memberTableColumns[i]))cols.splice(i,0,settingsDefault.memberTableColumns[i])}else{let x=cols.indexOf(settingsDefault.memberTableColumns[i]);if(x>=0)cols.splice(x,1)}db.settings.memberTableColumns=cols;save();renderSettings();renderMembers()}
window.addActivityConfig=()=>{modal('إضافة نشاط','<div class="formgrid">'+fld('رمز النشاط','acCode')+fld('اسم النشاط','acName')+'<div class="field"><label>الباقة المرتبطة</label>'+sel('acPack',Object.keys(db.packs).filter(k=>k!=='A'))+'</div><div class="field"><label>ترتيب النشاط</label>'+fld('','acOrder','6')+'</div><div class="field full notice">الباقة B–F تتكون من قيمة A + التأمين الخاص بالنشاط + مساهمة العتاد. هذه مكونات مالية قابلة للإعداد وليست حكماً قانونياً بذاتها.</div></div><div class="actions">'+btn('حفظ',"saveActivityConfig()")+'</div>')}
window.saveActivityConfig=()=>{let code=document.getElementById('acCode').value.trim().toUpperCase(),name=document.getElementById('acName').value.trim(),pack=document.getElementById('acPack').value,order=Number(document.getElementById('acOrder').value)||1;if(!code||!name||!pack)return alert('أكمل البيانات');if(db.activityCatalog.some(x=>String(x.code)===code))return alert('رمز النشاط مستعمل');db.activityCatalog.push({code,name,pack,order,active:true});save();document.querySelector('.modalback')?.remove();go('settings')}
window.editActivityConfig=code=>{let a=activityByCode(code),p=db.packs[a?.pack]||{};if(!a)return;modal('تعديل النشاط','<div class="formgrid">'+fld('رمز النشاط','acCode',a.code)+fld('اسم النشاط','acName',a.name)+'<div class="field"><label>الباقة المرتبطة</label>'+sel('acPack',Object.keys(db.packs).filter(k=>k!=='A'),a.pack)+'</div>'+fld('ترتيب النشاط','acOrder',a.order)+'</div><div class="actions">'+btn('حفظ',"saveEditedActivity('"+esc(code)+"')")+'</div>')}
window.saveEditedActivity=old=>{let a=activityByCode(old);if(!a)return;let code=document.getElementById('acCode').value.trim().toUpperCase(),name=document.getElementById('acName').value.trim(),pack=document.getElementById('acPack').value,order=Number(document.getElementById('acOrder').value)||1;if(!code||!name||!pack)return alert('أكمل البيانات');if(code!==old&&db.activityCatalog.some(x=>String(x.code)===code))return alert('رمز النشاط مستعمل');a.code=code;a.name=name;a.pack=pack;a.order=order;save();document.querySelector('.modalback')?.remove();go('settings')}
window.toggleActivityConfig=code=>{let a=activityByCode(code);if(!a)return;a.active=a.active===false;save();go('settings')}
window.savePackA=()=>{let v=parseMoney(document.getElementById('paValue')?.value||0);if(!v)return alert('قيمة A مطلوبة');db.packs.A.d=document.getElementById('paDesc').value.trim()||'الاشتراك السنوي القانوني';db.packs.A.v=v;db.packs.A.legal=true;Object.entries(db.packs).forEach(([k,p])=>{if(k!=='A')p.v=packTotal(p)});save();go('settings')}
window.editActivityPack=pack=>{let p=db.packs[pack];if(!p||pack==='A')return;modal('تعديل باقة '+pack,'<div class="formgrid">'+fld('تسمية الباقة','pd',p.d)+moneyInput('pi',p.insurance||0)+moneyInput('pe',p.equipment||0)+'</div><div class="notice">الإجمالي = A + التأمين + مساهمة العتاد. لا نثبت أي وصف قانوني للتكاليف؛ يجب أن يكون اعتمادها وفق الإطار القانوني والتنظيمي للجمعية.</div><div class="actions">'+btn('حفظ',"saveActivityPack('"+pack+"')")+'</div>')}
window.saveActivityPack=pack=>{let p=db.packs[pack];if(!p)return;p.d=document.getElementById('pd').value.trim()||p.d;p.insurance=parseMoney(document.getElementById('pi').value||0);p.equipment=parseMoney(document.getElementById('pe').value||0);p.v=packTotal(p);save();document.querySelector('.modalback')?.remove();go('settings')}
window.addSetting=()=>{let k=sk.value,v=sv.value.trim();if(!v)return;if(!db.settings[k].includes(v))db.settings[k].push(v);save();go('settings')};window.removeSetting=(k,i)=>{db.settings[k].splice(i,1);save();go('settings')};window.closeYear=y=>{if(confirm('إغلاق السنة '+y+'؟')){if(db.years[y]?.status!=='open')return;db.years[y].status='closed';db.years[y].closing=bal(y);save();go('settings')}}
window.backup=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='نسخة_احتياطية_جمعية_الأفق_V1.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
shell();save();
})();