(function(){
'use strict';
const V8KEY='afak_platform_v8';
let S=JSON.parse(localStorage.getItem(V8KEY)||'null')||{
  yearMeta:{'2025':{status:'closed',opening:0,note:'السنة التأسيسية — موثقة تاريخياً'}},
  plans:[], activities:[], assets:[], loans:[], maintenance:[], incoming:[], outgoing:[], correspondence:[], documents:[], meetings:[], decisions:[], tasks:[], audit:[]
};
function saveV8(){localStorage.setItem(V8KEY,JSON.stringify(S));}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function money(n){return Number(n||0).toLocaleString('ar-DZ')+' دج';}
function members(){return Array.isArray(window.db.members)?window.db.members:[]}
function years(){let ys=new Set(['2025',String(new Date().getFullYear())]); Object.keys(S.yearMeta||{}).forEach(y=>ys.add(String(y))); (window.db.finance||[]).forEach(x=>{let y=String(x.financialYear||x.date||'').slice(0,4);if(/^\d{4}$/.test(y))ys.add(y)}); S.plans.forEach(x=>ys.add(String(x.year))); S.activities.forEach(x=>ys.add(String(x.year))); return [...ys].sort((a,b)=>+a-+b);}
function fy(y){y=String(y); let m=S.yearMeta[y]; if(!m){let prev=years().filter(x=>+x<+y).sort((a,b)=>+b-+a)[0]; let opening=prev?closeBal(prev):0; m=S.yearMeta[y]={status:'open',opening,createdAt:new Date().toISOString().slice(0,10)}; saveV8();} return m;}
function closeBal(y){let m=S.yearMeta[String(y)]||{};let open=+m.opening||0;let fs=(window.db.finance||[]).filter(x=>String(x.financialYear||x.date||'').slice(0,4)===String(y)&&!x.voided);let inc=fs.filter(x=>x.type!=='مصروف').reduce((a,x)=>a+(+x.amount||0),0);let exp=fs.filter(x=>x.type==='مصروف').reduce((a,x)=>a+(+x.amount||0),0);return open+inc-exp;}
function log(action,entity,id,detail){S.audit.unshift({id:'AUD-'+Date.now(),date:new Date().toISOString(),action,entity,id:id||'',detail:detail||''});S.audit=S.audit.slice(0,500);saveV8();}
function statusBadge(x){return `<span class="v8badge">${esc(x||'—')}</span>`}
function memberName(no){return members().find(m=>m.no===no)?.name||no||'—'}
function activityTitle(id){return S.activities.find(a=>a.id===id)?.title||id||'—'}
function yearSelect(id,value,all=false){return `<select id="${id}">${all?'<option value="">كل السنوات</option>':''}${years().map(y=>`<option value="${y}" ${String(y)===String(value)?'selected':''}>${y}</option>`).join('')}</select>`}
function page(id,title,body){return `<section class="v8page" id="v8-${id}"><div class="v8title"><div><h2>${title}</h2><small>منصة جمعية الأفق — النظام المتكامل</small></div></div>${body}</section>`}
function shell(){
 document.querySelector('.app')?.classList.add('v8hidden'); document.querySelectorAll('body>.bottom').forEach(x=>x.classList.add('v8hidden'));
 let root=document.getElementById('v8app'); if(root)return;
 root=document.createElement('div');root.id='v8app';document.body.appendChild(root);
 root.innerHTML=`<header class="v8top"><div><b>جمعية الأفق للرياضات الجوية والجبلية</b><small>منصة التسيير المتكاملة — الإصدار 8.1</small></div><button onclick="v8Backup()">نسخة احتياطية</button></header>
 <div class="v8layout"><aside class="v8nav"><button onclick="v8go('dash')">⌂ لوحة القيادة</button><button onclick="v8go('members')">👥 الأعضاء</button><button onclick="v8go('memberships')">🪪 العضويات</button><button onclick="v8go('planning')">🗓️ التخطيط</button><button onclick="v8go('activities')">🏔️ الأنشطة</button><button onclick="v8go('finance')">💰 المالية</button><button onclick="v8go('assets')">🧰 المعدات</button><button onclick="v8go('incoming')">📥 البريد الوارد</button><button onclick="v8go('outgoing')">📤 البريد الصادر</button><button onclick="v8go('correspondence')">📁 المراسلات</button><button onclick="v8go('governance')">🛡️ الحوكمة</button><button onclick="v8go('documents')">📄 الوثائق</button><button onclick="v8go('reports')">📊 التقارير</button><button onclick="v8go('settings')">⚙️ الإعدادات</button><hr><button onclick="v8legacy('training')">🎓 التكوينات</button><button onclick="v8legacy('attendance')">🕐 الحضور</button><button onclick="v8legacy('certificates')">📜 الشهادات</button></aside><main id="v8main"></main></div>`;
 renderAll();v8go('dash');
}
function renderAll(){let m=v8members(),ms=v8memberships(),p=v8planning(),a=v8activities(),f=v8finance(),eq=v8assets(),gov=v8gov(),mail=v8mail(),docs=v8documents(),rep=v8reports(),set=v8settings(); document.getElementById('v8main').innerHTML=m+ms+p+a+f+eq+mail+gov+docs+rep+set; bind();}
function v8go(id){document.querySelectorAll('.v8page').forEach(x=>x.style.display='none');let x=document.getElementById('v8-'+id);if(x)x.style.display='block';}
function v8legacy(id){document.querySelector('.app')?.classList.remove('v8hidden');document.getElementById('v8app')?.classList.add('v8hidden'); if(typeof show==='function')show(id);}
window.v8go=v8go;window.v8legacy=v8legacy;
function v8members(){let a=members(),active=a.filter(m=>(m.memberStatus||'نشط')==='نشط');return page('members','معلومات المنخرطين','<div class="v8cards"><div><b>'+active.length+'</b><small>المنخرطون النشطون</small></div><div><b>'+active.filter(m=>m.officeRole).length+'</b><small>أعضاء المكتب</small></div><div><b>'+a.filter(m=>(m.memberStatus||'نشط')!=='نشط').length+'</b><small>غير نشطين</small></div></div><div class="v8bar"><input id="v8mq" placeholder="بحث بالاسم أو الرقم"><button onclick="v8AddMember()">+ إضافة منخرط</button></div><div class="v8notice">بيانات المنخرط فقط؛ الاشتراك السنوي والتسديد والمزاولة في صفحة العضويات.</div><div id="v8membertable"></div>')}
function renderMemberTable(){let q=(document.getElementById('v8mq')?.value||'').toLowerCase();let arr=members().filter(m=>!q||String(m.name).toLowerCase().includes(q)||String(m.no).includes(q)).slice().sort((a,b)=>(a.officeRole?0:1)-(b.officeRole?0:1));document.getElementById('v8membertable').innerHTML=`<div class="v8table"><table><thead><tr><th>الرقم</th><th>العضو</th><th>الصفة</th><th>تاريخ الانضمام</th><th>حالة العضوية</th><th>المالية</th><th></th></tr></thead><tbody>${arr.map(m=>{let c=typeof memberCalc==='function'?memberCalc(m):{status:'—',total:0};return `<tr><td>${esc(m.no)}</td><td><b>${esc(m.name)}</b><small>${esc(m.type||'')}</small></td><td>${esc(m.officeRole||'—')}</td><td>${esc(m.joinDate||'—')}</td><td>${statusBadge(m.adminStatus||'غير مكتملة')}</td><td>${esc(c.status)}<br><small>${money(c.total)}</small></td><td><button class="v8sm" onclick="window.v8Member(this.dataset.no)" data-no="${esc(m.no)}">فتح الملف</button></td></tr>`}).join('')}</tbody></table></div>`}
function v8AddMember(){let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>إضافة عضو</h3><div class="v8form"><label>الاسم واللقب<input id="vm_name"></label><label>الهاتف<input id="vm_phone"></label><label>تاريخ الميلاد<input id="vm_dob" type="date"></label><label>تاريخ الانضمام<input id="vm_join" type="date" value="2025-08-31"></label><label>نوع العضوية<select id="vm_type">${(window.settings.membershipTypes||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>الصفة في المكتب<select id="vm_role"><option value="">—</option><option>الرئيس</option><option>نائب الرئيس</option><option>الأمين العام</option><option>أمين المال</option><option>نائب أمين المال</option></select></label><label>المهنة<input id="vm_job"></label><label>العنوان<input id="vm_address"></label><label>ملاحظات<textarea id="vm_notes"></textarea></label></div><p class="v8notice">إضافة العضو لا تنشئ حركة مالية تلقائياً. تسجل الحركة فقط عند وجود قبض فعلي.</p><button onclick="v8SaveNewMember()">حفظ العضو</button></div></div>`;document.body.appendChild(box)}
function v8SaveNewMember(){let name=document.getElementById('vm_name').value.trim();if(!name)return alert('أدخل الاسم واللقب');let no=nextMemberNoValue();let m={no,name,phone:document.getElementById('vm_phone').value,dob:document.getElementById('vm_dob').value,email:'',birthPlace:'',gender:'ذكر',address:document.getElementById('vm_address').value,joinDate:document.getElementById('vm_join').value||new Date().toISOString().slice(0,10),adminStatus:'غير مكتملة',officeRole:document.getElementById('vm_role').value,occupation:document.getElementById('vm_job').value,type:document.getElementById('vm_type').value,pack:'',year:String(new Date().getFullYear()),paid:0,method:'',date:'',photo:'',notes:document.getElementById('vm_notes').value};window.db.members.push(m);ensureMemberships();save();log('إضافة','عضو',m.no,m.name);document.querySelector('.v8modal')?.remove();renderAll();v8go('members')}
function nextMemberNoValue(){let nums=members().map(m=>parseInt(String(m.no).replace(/\D/g,''),10)).filter(Number.isFinite);return String((nums.length?Math.max(...nums):0)+1).padStart(4,'0')}
function v8Member(no){let m=members().find(x=>x.no===no);if(!m)return;let c=typeof memberCalc==='function'?memberCalc(m):{};let lock=(m.adminStatus||'').includes('فعالة');let html=`<div class="v8modal"><div class="v8modalbox"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>${esc(m.name)}</h3><p>${esc(m.officeRole||m.type||'عضو')}</p><div class="v8kv"><span>رقم العضوية<b>${esc(m.no)}</b></span><span>الانضمام<b>${esc(m.joinDate||'—')}</b></span><span>الحالة<b>${esc(m.adminStatus||'—')}</b></span><span>التسديد<b>${esc(c.status||'—')}</b></span><span>المدفوع<b>${money(c.total||0)}</b></span><span>التخصص<b>${esc(m.pack||'غير محدد')}</b></span></div><div class="v8bar"><button onclick="v8MemberEdit('${esc(m.no)}',${lock})">${lock?'🔒 العضوية مفعلة — تعديل بإجراء خاص':'✏️ تعديل البيانات'}</button><button onclick="v8go('memberships');v8OpenMembership('${esc(m.no)}')">العضويات</button><button onclick="v8go('finance');document.getElementById('v8fmember').value='${esc(m.no)}';v8RenderFinance()">المالية</button></div><hr><h4>السجل المرتبط</h4><p>أنشطة: ${S.activities.filter(a=>a.participants?.includes(m.no)).length} — دفعات: ${(window.db.finance||[]).filter(f=>f.member===m.no).length} — حضور: ${(window.db.attendance||[]).filter(x=>x.member===m.no).length} — شهادات: ${(window.db.certificates||[]).filter(x=>x.member===m.no).length}</p></div></div>`;document.body.insertAdjacentHTML('beforeend',html)}
function v8MemberEdit(no,locked){if(locked){alert('هذه العضوية مفعلة. استخدم إجراء طلب تعديل/فتح اعتماد بدلاً من التعديل المباشر.');return;} if(typeof editMember==='function'){document.querySelector('.v8modal')?.remove();v8legacy('members');editMember(no)}}
function v8memberships(){return page('memberships','العضويات السنوية',`<div class="v8bar"><label>السنة ${yearSelect('v8msyear',new Date().getFullYear(),true)}</label><select id="v8mspack"><option value="">كل الباقات</option>${Object.entries(window.packs).map(([k,p])=>`<option value="${k}">${k} — ${esc(p.d)}</option>`).join('')}</select></div><div id="v8mst"></div>`)}
function v8OpenMembership(no){
  let m=members().find(x=>x.no===no); if(!m)return;
  let y=document.getElementById('v8msyear')?.value||String(new Date().getFullYear());
  let r=membershipRecord(m,y)||{};
  let pack=r.pack||m.pack||'';
  let c=typeof membershipCalc==='function'?membershipCalc(m,y,pack):{due:0,total:0,balance:0,status:'—',activity:'—'};
  let box=document.createElement('div'); box.className='v8modal';
  box.innerHTML=`<div class="v8modalbox">
    <button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button>
    <h3>ملف العضوية السنوية</h3>
    <div class="v8kv">
      <span>العضو<b>${esc(m.name)}</b></span>
      <span>رقم العضوية<b>${esc(m.no)}</b></span>
      <span>السنة<b>${esc(y)}</b></span>
      <span>الباقة<b>${esc(pack||'غير محددة')}</b></span>
      <span>المستحق<b>${money(c.due||0)}</b></span>
      <span>المدفوع<b>${money(c.total||0)}</b></span>
      <span>المتبقي<b>${c.balance?money(c.balance):'\\'}</b></span>
      <span>الحالة<b>${esc(c.status||'—')}</b></span>
      <span>المزاولة<b>${esc(c.activity||'—')}</b></span>
    </div>
    <div class="v8bar">
      <button onclick="v8EditMembershipSelection('${esc(m.no)}','${esc(y)}');this.parentElement.parentElement.parentElement.remove()">تعديل/فتح العضوية</button>
      <button class="v8sm" onclick="v8Member('${esc(m.no)}');this.parentElement.parentElement.parentElement.remove()">فتح ملف العضو الكامل</button>
    </div>
  </div></div>`;
  document.body.appendChild(box);
}
function v8EditMembershipSelection(no,year){
  let y=document.getElementById('v8msyear'),s=document.getElementById('v8mspack');
  if(y)y.value=year;
  let m=members().find(x=>x.no===no),r=m?membershipRecord(m,year):null;
  if(s)s.value=r?.pack||m?.pack||'';
  v8RenderMemberships();
}
function renderMemberships(){let y=document.getElementById('v8msyear')?.value||String(new Date().getFullYear()),pack=document.getElementById('v8mspack')?.value||'';let arr=members().map(m=>{let r=(window.db.memberships||[]).find(x=>x.member===m.no&&String(x.year)===String(y));let c=typeof membershipCalc==='function'?membershipCalc(m,y,r?.pack||m.pack||''):{due:0,total:0,balance:0,status:'—',activity:'—'};return {m,r,c}}).filter(x=>!pack||x.r?.pack===pack||x.m.pack===pack);document.getElementById('v8mst').innerHTML=`<div class="v8table"><table><thead><tr><th>العضو</th><th>الباقة</th><th>المستحق</th><th>المدفوع</th><th>الباقي</th><th>الحالة</th><th>المزاولة</th><th></th></tr></thead><tbody>${arr.map(x=>`<tr><td>${esc(x.m.name)}</td><td>${esc(x.r?.pack||x.m.pack||'—')}</td><td>${money(x.c.due||0)}</td><td>${money(x.c.total||0)}</td><td>${x.c.balance?money(x.c.balance):'\\'}</td><td>${esc(x.c.status)}</td><td>${esc(x.c.activity)}</td><td><button class="v8sm" onclick="v8OpenMembership('${esc(x.m.no)}')">فتح</button></td></tr>`).join('')}</tbody></table></div>`}
function v8planning(){return page('planning','التخطيط السنوي',`<div class="v8bar"><button onclick="v8PlanForm()">+ إضافة نشاط إلى الخطة</button>${yearSelect('v8pyear',new Date().getFullYear(),true)}</div><div id="v8plant"></div>`)}
function v8PlanForm(){let y=document.getElementById('v8pyear')?.value||new Date().getFullYear();let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>إضافة نشاط إلى البرنامج السنوي</h3><div class="v8form"><label>العنوان<input id="pf_title"></label><label>السنة<input id="pf_year" value="${y}" type="number"></label><label>التخصص<select id="pf_spec">${(window.settings.activityTypes||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>التاريخ المتوقع<input id="pf_date" type="date"></label><label>التكلفة التقديرية<input id="pf_budget" type="number" min="0"></label><label>الأولوية<select id="pf_priority"><option>عادية</option><option>مرتفعة</option><option>عاجلة</option></select></label><label>المسؤول<select id="pf_owner"><option value="">— اختر عضواً —</option>${members().map(m=>`<option value="${m.no}">${esc(m.name)}</option>`).join("")}</select></label><label>ملاحظات<textarea id="pf_notes"></textarea></label></div><button onclick="v8SavePlan()">حفظ الخطة</button></div></div>`;document.body.appendChild(box)}
function v8SavePlan(){let x={id:'PL-'+Date.now(),title:pf_title.value,year:+pf_year.value,specialty:pf_spec.value,date:pf_date.value,budget:+pf_budget.value||0,priority:pf_priority.value,owner:pf_owner.value,status:'مقترح',notes:pf_notes.value,createdAt:new Date().toISOString().slice(0,10)};if(!x.title)return alert('أدخل عنوان النشاط');S.plans.push(x);saveV8();log('إضافة','خطة',x.id,x.title);document.querySelector('.v8modal')?.remove();renderAll();v8go('planning')}
function renderPlanning(){let y=document.getElementById('v8pyear')?.value||'';let arr=S.plans.filter(x=>!y||String(x.year)===String(y));document.getElementById('v8plant').innerHTML=`<div class="v8table"><table><thead><tr><th>العنوان</th><th>السنة</th><th>التاريخ</th><th>التقديري</th><th>المصدر</th><th>الحالة</th><th></th></tr></thead><tbody>${arr.map(x=>`<tr><td>${esc(x.title)}</td><td>${x.year}</td><td>${esc(x.date||'—')}</td><td>${money(x.budget)}</td><td>البرنامج السنوي</td><td>${statusBadge(x.status)}</td><td><button class="v8sm" onclick="v8ConvertPlan('${x.id}')">إنشاء نشاط</button></td></tr>`).join('')}</tbody></table></div>`}
function v8ConvertPlan(id){let p=S.plans.find(x=>x.id===id);if(!p)return;let existing=S.activities.find(a=>a.planId===id);if(existing){v8Activity(existing.id);return;}let a={id:'ACT-'+Date.now(),title:p.title,year:p.year,specialty:p.specialty,type:'',date:p.date,location:'',responsible:p.owner,status:'مبرمج',source:'البرنامج السنوي',planId:id,estimated:p.budget||0,actualIncome:0,participants:[],instructors:[],assets:[],reason:'',createdAt:new Date().toISOString().slice(0,10)};S.activities.push(a);p.status='مبرمج';saveV8();log('إنشاء نشاط','نشاط',a.id,a.title);renderAll();v8go('activities')}
function v8activities(){return page('activities','الأنشطة',`<div class="v8bar"><button onclick="v8ActivityForm()">+ إضافة نشاط</button>${yearSelect('v8ayear',new Date().getFullYear(),true)}<select id="v8astatus"><option value="">كل الحالات</option><option>مقترح</option><option>مبرمج</option><option>قيد التنفيذ</option><option>منجز</option><option>مؤجل</option><option>ملغى لأسباب</option></select><select id="v8asource"><option value="">كل المصادر</option><option>البرنامج السنوي</option><option>خارج البرنامج السنوي</option></select></div><div id="v8act"></div>`)}
function v8ActivityForm(){let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>إضافة نشاط</h3><div class="v8form"><label>مصدر النشاط<select id="af_source"><option>البرنامج السنوي</option><option>خارج البرنامج السنوي</option></select></label><label>العنوان<input id="af_title"></label><label>السنة<input id="af_year" type="number" value="${new Date().getFullYear()}"></label><label>التخصص<select id="af_spec">${(window.settings.activityTypes||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>نوع الفعالية<select id="af_type">${(window.settings.eventTypes||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>التاريخ<input id="af_date" type="date"></label><label>المكان<input id="af_location"></label><label>المسؤول<select id="af_owner"><option value="">— اختر عضواً —</option>${members().map(m=>`<option value="${m.no}">${esc(m.name)}</option>`).join("")}</select></label><label>التكلفة التقديرية<input id="af_budget" type="number" min="0"></label><label id="af_reason_box">سبب الاستحداث<textarea id="af_reason"></textarea></label></div><button onclick="v8SaveActivity()">حفظ النشاط</button></div></div>`;document.body.appendChild(box)}
function v8SaveActivity(){let x={id:'ACT-'+Date.now(),title:af_title.value,year:+af_year.value,specialty:af_spec.value,type:af_type.value,date:af_date.value,location:af_location.value,responsible:af_owner.value,status:'مقترح',source:af_source.value,estimated:+af_budget.value||0,actualIncome:0,participants:[],instructors:[],assets:[],reason:af_reason.value,createdAt:new Date().toISOString().slice(0,10),planId:''};if(x.source==='البرنامج السنوي'){let p=S.plans.find(p=>p.year===x.year&&p.title===x.title&&!S.activities.some(a=>a.planId===p.id));if(p){x.planId=p.id;p.status='مبرمج';}}if(x.source==='خارج البرنامج السنوي'&&!x.reason.trim())return alert('يجب تسجيل سبب استحداث نشاط خارج البرنامج');if(!x.title)return alert('أدخل عنوان النشاط');S.activities.push(x);saveV8();log('إضافة','نشاط',x.id,x.title);document.querySelector('.v8modal')?.remove();renderAll();v8go('activities')}
function renderActivities(){let y=document.getElementById('v8ayear')?.value||'',st=document.getElementById('v8astatus')?.value||'',src=document.getElementById('v8asource')?.value||'';let arr=S.activities.filter(x=>(!y||String(x.year)===String(y))&&(!st||x.status===st)&&(!src||x.source===src));document.getElementById('v8act').innerHTML=`<div class="v8table"><table><thead><tr><th>النشاط</th><th>التاريخ</th><th>المصدر</th><th>التقديري</th><th>الفعلي</th><th>الحالة</th><th></th></tr></thead><tbody>${arr.map(x=>{let fs=(window.db.finance||[]).filter(f=>f.activityId===x.id&&!f.voided);let actual=fs.filter(f=>f.type==='مصروف').reduce((s,f)=>s+(+f.amount||0),0);return `<tr><td><b>${esc(x.title)}</b><small>${esc(x.specialty)} — ${esc(x.location)}</small></td><td>${esc(x.date||'—')}</td><td>${esc(x.source)}</td><td>${money(x.estimated)}</td><td>${money(actual)}</td><td>${statusBadge(x.status)}</td><td><button class="v8sm" onclick="v8Activity('${x.id}')">فتح الملف</button></td></tr>`}).join('')}</tbody></table></div>`}
function v8Activity(id){let x=S.activities.find(a=>a.id===id);if(!x)return;let fs=(window.db.finance||[]).filter(f=>f.activityId===id&&!f.voided),exp=fs.filter(f=>f.type==='مصروف').reduce((s,f)=>s+(+f.amount||0),0),inc=fs.filter(f=>f.type!=='مصروف').reduce((s,f)=>s+(+f.amount||0),0);let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox wide"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>${esc(x.title)}</h3><div class="v8cards"><div><b>${esc(x.status)}</b><small>الحالة</small></div><div><b>${money(x.estimated)}</b><small>التقديري</small></div><div><b>${money(exp)}</b><small>المصروف الفعلي</small></div><div><b>${money(inc)}</b><small>المداخيل الفعلية</small></div></div><div class="v8kv"><span>المصدر<b>${esc(x.source)}</b></span><span>التاريخ<b>${esc(x.date||'—')}</b></span><span>التخصص<b>${esc(x.specialty)}</b></span><span>المكان<b>${esc(x.location||'—')}</b></span><span>المسؤول<b>${esc(x.responsible||'—')}</b></span><span>سبب الاستحداث<b>${esc(x.reason||'—')}</b></span></div><div class="v8bar"><select id="v8actstatus"><option ${x.status==='مقترح'?'selected':''}>مقترح</option><option ${x.status==='مبرمج'?'selected':''}>مبرمج</option><option ${x.status==='قيد التنفيذ'?'selected':''}>قيد التنفيذ</option><option ${x.status==='منجز'?'selected':''}>منجز</option><option ${x.status==='مؤجل'?'selected':''}>مؤجل</option><option ${x.status==='ملغى لأسباب'?'selected':''}>ملغى لأسباب</option></select><button onclick="v8SetActivityStatus('${x.id}')">تحديث الحالة</button><button onclick="v8go('finance');setTimeout(()=>{document.getElementById('v8factivity').value='${x.id}';v8RenderFinance()},50)">المالية</button></div><hr><h4>المشاركون</h4><p>${x.participants?.length||0} مسجلون — <button class="v8sm" onclick="v8AddParticipant('${x.id}')">إضافة مشارك</button></p><div>${(x.participants||[]).map(no=>`<span class="v8tag">${esc(memberName(no))}</span>`).join(' ')||'لا يوجد'}</div><h4>المعدات</h4><p>${(x.assets||[]).map(id=>esc(S.assets.find(a=>a.id===id)?.name||id)).join('، ')||'لا توجد'}</p><h4>الحركات المالية</h4><div class="v8table"><table><thead><tr><th>التاريخ</th><th>البيان</th><th>النوع</th><th>المبلغ</th></tr></thead><tbody>${fs.map(f=>`<tr><td>${esc(f.date||'—')}</td><td>${esc(f.desc||'')}</td><td>${f.type==='مصروف'?'دفع':'قبض'}</td><td>${money(f.amount)}</td></tr>`).join('')||'<tr><td colspan="4">لا توجد حركات</td></tr>'}</tbody></table></div></div>`;document.body.appendChild(box)}
function v8SetActivityStatus(id){let x=S.activities.find(a=>a.id===id);if(!x)return;x.status=document.getElementById('v8actstatus').value;saveV8();log('تغيير حالة','نشاط',id,x.status);document.querySelector('.v8modal')?.remove();renderAll();v8go('activities')}
function v8AddParticipant(id){let opts=members().map(m=>`${m.no} — ${m.name}`).join('\n');let no=prompt('أدخل رقم العضو من القائمة:\n'+opts);if(!no)return;let x=S.activities.find(a=>a.id===id);if(!x)return;if(!members().some(m=>m.no===no))return alert('رقم العضو غير موجود');x.participants=x.participants||[];if(x.participants.includes(no))return alert('العضو مسجل بالفعل');x.participants.push(no);saveV8();log('إضافة مشارك','نشاط',id,no);document.querySelector('.v8modal')?.remove();v8Activity(id)}
function v8finance(){return page('finance','السجل المالي الموحد',`<div class="v8cards" id="v8fsummary"></div><div class="v8bar"><button onclick="v8FinanceForm()">+ إضافة حركة مالية</button>${yearSelect('v8fyear',new Date().getFullYear(),true)}<select id="v8fkind"><option value="">كل الحركات</option><option>قبض</option><option>دفع</option></select><input id="v8fmember" placeholder="رقم العضو" value=""><select id="v8factivity"><option value="">كل الأنشطة</option>${S.activities.map(a=>`<option value="${a.id}">${esc(a.title)}</option>`).join('')}</select></div><div id="v8ftable"></div>`)}
function v8FinanceForm(){let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>إضافة حركة مالية</h3><div class="v8form"><label>نوع الحركة<select id="ff_kind"><option>قبض</option><option>دفع</option></select></label><label>التاريخ<input id="ff_date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>السنة المالية<input id="ff_year" type="number" value="${new Date().getFullYear()}"></label><label>المبلغ<input id="ff_amount" type="number" min="0"></label><label>البيان<input id="ff_desc"></label><label>التصنيف<select id="ff_cat">${(window.settings.financeCategories||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>طريقة الدفع<select id="ff_method">${(window.settings.paymentMethods||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>الحساب<select id="ff_account">${(window.settings.accounts||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>العضو (اختياري)<select id="ff_member"><option value="">—</option>${members().map(m=>`<option value="${m.no}">${esc(m.name)}</option>`).join('')}</select></label><label>النشاط (اختياري)<select id="ff_activity"><option value="">—</option>${S.activities.map(a=>`<option value="${a.id}">${esc(a.title)}</option>`).join('')}</select></label><label>اقتناء معدة؟<select id="ff_asset"><option value="no">لا</option><option value="yes">نعم</option></select></label><div id="ff_asset_fields"></div></div><button onclick="v8SaveFinance()">تسجيل الحركة</button></div></div>`;document.body.appendChild(box);ff_asset.onchange=v8AssetFields}
function v8AssetFields(){let on=ff_asset.value==='yes';document.getElementById('ff_asset_fields').innerHTML=on?`<label>اسم المعدة<input id="ff_aname"></label><label>نوعها<input id="ff_atype"></label><label>رقم الجرد<input id="ff_ano"></label><label>التخصص<select id="ff_aspec">${(window.settings.activityTypes||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>مكان الحفظ<input id="ff_aloc"></label>`:''}
function v8SaveFinance(){let year=String(ff_year.value),meta=fy(year);if(meta.status==='closed')return alert('السنة مغلقة. لا يمكن إضافة حركة مالية.');let amt=+ff_amount.value||0;if(amt<=0)return alert('أدخل مبلغاً صحيحاً');let f={id:nextId('OP-',window.db.finance),type:ff_kind.value==='دفع'?'مصروف':'دخل غير اشتراكات',category:ff_cat.value,nature:ff_kind.value==='قبض'?'دخل غير اشتراكات':'مصروف الجمعية',member:ff_member.value,membershipId:'',membershipYear:ff_member.value?year:'',activityId:ff_activity.value,party:'',amount:amt,date:ff_date.value,financialYear:year,method:ff_method.value,account:ff_account.value,desc:ff_desc.value,ref:'',voided:false};window.db.finance.push(f);save();log('إضافة','حركة مالية',f.id,f.desc);if(ff_asset.value==='yes'&&ff_kind.value==='دفع'){let a={id:'AST-'+Date.now(),name:ff_aname.value,type:ff_atype.value,inventoryNo:ff_ano.value,serial:'',acquisitionDate:ff_date.value,source:'شراء',value:amt,specialty:ff_aspec.value,location:ff_aloc.value,status:'في الخدمة',financeId:f.id,notes:''};S.assets.push(a);f.assetId=a.id;saveV8();log('إنشاء','معدة',a.id,a.name)}document.querySelector('.v8modal')?.remove();renderAll();v8go('finance')}
function renderFinance(){let y=document.getElementById('v8fyear')?.value||'',kind=document.getElementById('v8fkind')?.value||'',mn=document.getElementById('v8fmember')?.value||'',aid=document.getElementById('v8factivity')?.value||'';let arr=(window.db.finance||[]).filter(f=>!f.voided&&(!y||String(f.financialYear||f.date||'').slice(0,4)===String(y))&&(!kind||(kind==='قبض'?f.type!=='مصروف':f.type==='مصروف'))&&(!mn||f.member===mn)&&(!aid||f.activityId===aid)).sort((a,b)=>String(a.date).localeCompare(String(b.date)));let open=y?(fy(y).opening||0):0,inc=arr.filter(f=>f.type!=='مصروف').reduce((s,f)=>s+(+f.amount||0),0),exp=arr.filter(f=>f.type==='مصروف').reduce((s,f)=>s+(+f.amount||0),0);document.getElementById('v8fsummary').innerHTML=`<div><b>${money(open)}</b><small>الرصيد الافتتاحي</small></div><div><b>${money(inc)}</b><small>إجمالي القبض</small></div><div><b>${money(exp)}</b><small>إجمالي الدفع</small></div><div><b>${money(open+inc-exp)}</b><small>الرصيد الحالي</small></div>`;document.getElementById('v8ftable').innerHTML=`<div class="v8table"><table><thead><tr><th>التاريخ</th><th>رقم العملية</th><th>البيان</th><th>العضو</th><th>النشاط</th><th>قبض</th><th>دفع</th><th>الرصيد</th></tr></thead><tbody>${(()=>{let bal=open;return arr.map(f=>{let income=f.type!=='مصروف'?+f.amount:0,expense=f.type==='مصروف'?+f.amount:0;bal+=income-expense;return `<tr><td>${esc(f.date||'—')}</td><td>${esc(f.id)}</td><td>${esc(f.desc||f.category||'')}</td><td>${esc(memberName(f.member))}</td><td>${esc(activityTitle(f.activityId))}</td><td>${income?money(income):'—'}</td><td>${expense?money(expense):'—'}</td><td><b>${money(bal)}</b></td></tr>`}).join('')})()||'<tr><td colspan="8">لا توجد حركات</td></tr>'}</tbody></table></div>`}
function v8assets(){return page('assets','المعدات والممتلكات',`<div class="v8bar"><button onclick="v8AssetForm()">+ إضافة معدة</button><select id="v8eqstatus"><option value="">كل الحالات</option><option>في الخدمة</option><option>صيانة</option><option>غير متاحة</option><option>محالة على الخدمة</option><option>مفقودة</option></select></div><div id="v8eqtable"></div>`)}
function v8AssetForm(){let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>إضافة معدة</h3><div class="v8form"><label>الاسم<input id="eq_name"></label><label>النوع<input id="eq_type"></label><label>رقم الجرد<input id="eq_inv"></label><label>الرقم التسلسلي<input id="eq_serial"></label><label>تاريخ الاقتناء<input id="eq_date" type="date"></label><label>طريقة الاقتناء<select id="eq_source"><option>شراء</option><option>تبرع</option><option>إعانة/دعم</option><option>مساهمة</option><option>تحويل</option><option>صنع من الجمعية</option><option>أخرى</option></select></label><label>القيمة<input id="eq_value" type="number"></label><label>التخصص<select id="eq_spec">${(window.settings.activityTypes||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>مكان الحفظ<input id="eq_loc"></label><label>الحالة<select id="eq_status"><option>في الخدمة</option><option>صيانة</option><option>غير متاحة</option><option>محالة على الخدمة</option><option>مفقودة</option></select></label><label>ملاحظات<textarea id="eq_notes"></textarea></label></div><button onclick="v8SaveAsset()">حفظ المعدة</button></div></div>`;document.body.appendChild(box)}
function v8SaveAsset(){let a={id:'AST-'+Date.now(),name:eq_name.value,type:eq_type.value,inventoryNo:eq_inv.value,serial:eq_serial.value,acquisitionDate:eq_date.value,source:eq_source.value,value:+eq_value.value||0,specialty:eq_spec.value,location:eq_loc.value,status:eq_status.value,financeId:'',notes:eq_notes.value};if(!a.name)return alert('أدخل اسم المعدة');S.assets.push(a);saveV8();log('إضافة','معدة',a.id,a.name);document.querySelector('.v8modal')?.remove();renderAll();v8go('assets')}
function renderAssets(){let st=document.getElementById('v8eqstatus')?.value||'';let arr=S.assets.filter(a=>!st||a.status===st);document.getElementById('v8eqtable').innerHTML=`<div class="v8table"><table><thead><tr><th>المعدة</th><th>النوع</th><th>الجرد</th><th>الاقتناء</th><th>القيمة</th><th>التخصص</th><th>الحالة</th><th>المصدر</th><th></th></tr></thead><tbody>${arr.map(a=>`<tr><td><b>${esc(a.name)}</b></td><td>${esc(a.type)}</td><td>${esc(a.inventoryNo||'—')}</td><td>${esc(a.acquisitionDate||'—')}</td><td>${money(a.value)}</td><td>${esc(a.specialty)}</td><td>${statusBadge(a.status)}</td><td>${esc(a.source)}</td><td><button class="v8sm" onclick="v8AssetDetail('${a.id}')">فتح الملف</button></td></tr>`).join('')||'<tr><td colspan="9">لا توجد معدات</td></tr>'}</tbody></table></div>`}
function v8AssetDetail(id){let a=S.assets.find(x=>x.id===id);if(!a)return;let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox wide"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>${esc(a.name)}</h3><div class="v8kv"><span>النوع<b>${esc(a.type)}</b></span><span>رقم الجرد<b>${esc(a.inventoryNo||'—')}</b></span><span>الرقم التسلسلي<b>${esc(a.serial||'—')}</b></span><span>القيمة<b>${money(a.value)}</b></span><span>التخصص<b>${esc(a.specialty||'—')}</b></span><span>المصدر<b>${esc(a.source||'—')}</b></span><span>مكان الحفظ<b>${esc(a.location||'—')}</b></span><span>الحالة<b>${esc(a.status)}</b></span></div><div class="v8bar"><select id="eq_new_status"><option>في الخدمة</option><option>صيانة</option><option>غير متاحة</option><option>محالة على الخدمة</option><option>مفقودة</option></select><button onclick="v8ChangeAssetStatus('${a.id}')">تغيير الحالة</button><button onclick="v8Maintenance('${a.id}')">تسجيل صيانة</button><button onclick="v8Loan('${a.id}')">إعارة</button></div><h4>الصيانة</h4>${S.maintenance.filter(x=>x.assetId===a.id).map(x=>`<div class="v8list">${esc(x.date)} — ${esc(x.work)} — ${money(x.cost)} — ${esc(x.status)}</div>`).join('')||'<p>لا توجد صيانة مسجلة.</p>'}<h4>الإعارات</h4>${S.loans.filter(x=>x.assetId===a.id).map(x=>`<div class="v8list">${esc(memberName(x.member))} — ${esc(x.date)} → ${esc(x.returnDate||'مفتوحة')} — ${esc(x.status)}</div>`).join('')||'<p>لا توجد إعارات.</p>'}</div></div>`;document.body.appendChild(box);eq_new_status.value=a.status}
function v8ChangeAssetStatus(id){let a=S.assets.find(x=>x.id===id);if(!a)return;a.status=document.getElementById('eq_new_status').value;saveV8();log('تغيير حالة','معدة',id,a.status);document.querySelector('.v8modal')?.remove();renderAll();v8go('assets')}
function v8Maintenance(id){let work=prompt('وصف أعمال الصيانة');if(!work)return;let cost=+prompt('تكلفة الصيانة (إن وجدت)','0')||0;S.maintenance.push({id:'MNT-'+Date.now(),assetId:id,date:new Date().toISOString().slice(0,10),work,cost,status:'منفذة'});let a=S.assets.find(x=>x.id===id);if(a)a.status='في الخدمة';saveV8();log('صيانة','معدة',id,work);document.querySelector('.v8modal')?.remove();renderAll();v8go('assets')}
function v8Loan(id){let opts=members().map(m=>m.no+' — '+m.name).join('\n');let no=prompt('رقم العضو المستعير:\n'+opts);if(!no||!members().some(m=>m.no===no))return alert('العضو غير موجود');let a=S.assets.find(x=>x.id===id);S.loans.push({id:'LOAN-'+Date.now(),assetId:id,member:no,date:new Date().toISOString().slice(0,10),returnDate:'',status:'معارة'});if(a)a.status='غير متاحة';saveV8();log('إعارة','معدة',id,no);document.querySelector('.v8modal')?.remove();renderAll();v8go('assets')}
function v8mail(){return page('mail','البريد والمراسلات',`<div class="v8cards"><div><b>${S.incoming.length}</b><small>وارد</small></div><div><b>${S.outgoing.length}</b><small>صادر</small></div><div><b>${S.correspondence.length}</b><small>مراسلات إدارية</small></div></div><p class="notice">الوارد والصادر والمراسلات سجلات منفصلة في العرض، لكنها مترابطة داخلياً. إنشاء وثيقة مستقبلية يمكن أن ينشئ سجل الصادر دون إعادة كتابة البيانات.</p><div class="v8tabs"><button onclick="v8go('incoming')">البريد الوارد</button><button onclick="v8go('outgoing')">البريد الصادر</button><button onclick="v8go('correspondence')">المراسلات الإدارية</button></div>`)}
function v8incoming(){return page('incoming','البريد الوارد',`<div class="v8bar"><button onclick="v8MailForm('in')">+ تسجيل وارد</button></div><div id="v8intable"></div>`)}
function v8outgoing(){return page('outgoing','البريد الصادر',`<div class="v8bar"><button onclick="v8MailForm('out')">+ تسجيل صادر</button></div><div id="v8outtable"></div>`)}
function v8correspondence(){return page('correspondence','المراسلات الإدارية',`<div class="v8bar"><button onclick="v8MailForm('corr')">+ مراسلة إدارية</button></div><div id="v8corrtable"></div>`)}
function v8MailForm(kind){let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>${kind==='in'?'تسجيل بريد وارد':kind==='out'?'تسجيل بريد صادر':'إضافة مراسلة إدارية'}</h3><div class="v8form"><label>الرقم المرجعي<input id="mf_ref"></label><label>التاريخ<input id="mf_date" type="date"></label><label>الجهة<input id="mf_party"></label><label>الموضوع<input id="mf_subject"></label><label>النوع<input id="mf_type"></label><label>المسؤول<select id="mf_owner"><option value="">— اختر عضواً —</option>${members().map(m=>`<option value="${m.no}">${esc(m.name)}</option>`).join("")}</select></label><label>أجل الرد/الإجراء<input id="mf_deadline" type="date"></label><label>الحالة<input id="mf_status" value="مفتوح"></label><label>ملاحظات<textarea id="mf_notes"></textarea></label></div><button onclick="v8SaveMail('${kind}')">حفظ</button></div></div>`;document.body.appendChild(box)}
function v8SaveMail(kind){let base={id:(kind==='in'?'IN-':kind==='out'?'OUT-':'COR-')+Date.now(),ref:mf_ref.value,date:mf_date.value,party:mf_party.value,subject:mf_subject.value,type:mf_type.value,owner:mf_owner.value,deadline:mf_deadline.value,status:mf_status.value,notes:mf_notes.value};if(kind==='in')S.incoming.push(base);else if(kind==='out')S.outgoing.push(base);else S.correspondence.push(base);saveV8();log('إضافة',kind==='in'?'بريد وارد':kind==='out'?'بريد صادر':'مراسلة',base.id,base.subject);document.querySelector('.v8modal')?.remove();renderAll();v8go(kind==='in'?'incoming':kind==='out'?'outgoing':'correspondence')}
function v8governance(){return page('governance','الحوكمة والمتابعة',`<div class="v8tabs"><button onclick="v8MeetingForm()">+ اجتماع</button><button onclick="v8DecisionForm()">+ قرار</button><button onclick="v8TaskForm()">+ مهمة</button></div><h3>الاجتماعات</h3><div id="v8meet"></div><h3>القرارات</h3><div id="v8dec"></div><h3>المهام</h3><div id="v8tasks"></div>`)}
function v8MeetingForm(){v8SimpleForm('اجتماع','اجتماع','date','المكان','agenda','حفظ الاجتماع',x=>{x.id='MT-'+Date.now();S.meetings.push(x)})}
function v8DecisionForm(){v8SimpleForm('قرار','رقم القرار','due','المسؤول','text','حفظ القرار',x=>{x.id='DEC-'+Date.now();S.decisions.push(x)})}
function v8TaskForm(){v8SimpleForm('مهمة','العنوان','due','المسؤول','text','حفظ المهمة',x=>{x.id='TASK-'+Date.now();S.tasks.push(x)})}
function v8SimpleForm(title,l1,l2,l3,l4,button,cb){let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>${title}</h3><div class="v8form"><label>${l1}<input id="sf1"></label><label>${l2}<input id="sf2" type="date"></label><label>${l3}${l3==='المسؤول'?'<select id="sf3"><option value="">— اختر عضواً —</option>'+members().map(m=>'<option value="'+esc(m.no)+'">'+esc(m.name)+'</option>').join('')+'</select>':'<input id="sf3">'}</label><label>${l4}<textarea id="sf4"></textarea></label></div><button onclick="v8SaveSimple('${title}')">${button}</button></div></div>`;document.body.appendChild(box);window.__v8simple={cb,title}}
function v8SaveSimple(title){let x={title:sf1.value,date:sf2.value,owner:sf3.value,text:sf4.value,status:'مفتوح'};let c=window.__v8simple?.cb;c?.(x);saveV8();log('إضافة',title,x.id,x.title||x.text);document.querySelector('.v8modal')?.remove();renderAll();v8go('governance')}
function v8documents(){return page('documents','الوثائق',`<div class="v8bar"><button onclick="v8DocForm()">+ إضافة وثيقة</button></div><div id="v8doctable"></div>`)}
function v8DocForm(){let box=document.createElement('div');box.className='v8modal';box.innerHTML=`<div class="v8modalbox"><button class="v8close" onclick="this.parentElement.parentElement.remove()">×</button><h3>إضافة وثيقة</h3><div class="v8form"><label>رقم الوثيقة<input id="df_no"></label><label>التاريخ<input id="df_date" type="date"></label><label>النوع<input id="df_type"></label><label>العنوان<input id="df_title"></label><label>الارتباط<select id="df_link"><option value="">—</option>${S.activities.map(a=>`<option value="${a.id}">${esc(a.title)}</option>`).join('')}</select></label><label>ملاحظات<textarea id="df_notes"></textarea></label></div><button onclick="v8SaveDoc()">حفظ الوثيقة</button></div></div>`;document.body.appendChild(box)}
function v8SaveDoc(){let d={id:'DOC-'+Date.now(),number:df_no.value,date:df_date.value,type:df_type.value,title:df_title.value,link:df_link.value,notes:df_notes.value};S.documents.push(d);saveV8();log('إضافة','وثيقة',d.id,d.title);document.querySelector('.v8modal')?.remove();renderAll();v8go('documents')}
function v8reports(){return page('reports','التقارير والمؤشرات',`<div class="v8bar">${yearSelect('v8ryear',new Date().getFullYear())}<button onclick="v8PrintReport()">طباعة التقرير السنوي</button></div><div id="v8report"></div>`)}
function renderReports(){let y=document.getElementById('v8ryear')?.value||String(new Date().getFullYear()),m=fy(y),fs=(window.db.finance||[]).filter(f=>String(f.financialYear||f.date||'').slice(0,4)===String(y)&&!f.voided),inc=fs.filter(f=>f.type!=='مصروف').reduce((s,f)=>s+(+f.amount||0),0),exp=fs.filter(f=>f.type==='مصروف').reduce((s,f)=>s+(+f.amount||0),0),acts=S.activities.filter(a=>String(a.year)===String(y)),plans=S.plans.filter(a=>String(a.year)===String(y));document.getElementById('v8report').innerHTML=`<div class="v8cards"><div><b>${members().length}</b><small>الأعضاء</small></div><div><b>${plans.length}</b><small>أنشطة مخططة</small></div><div><b>${acts.length}</b><small>أنشطة مسجلة</small></div><div><b>${acts.filter(a=>a.status==='منجز').length}</b><small>منجزة</small></div><div><b>${money(inc)}</b><small>القبض</small></div><div><b>${money(exp)}</b><small>الدفع</small></div><div><b>${money((m.opening||0)+inc-exp)}</b><small>الرصيد</small></div><div><b>${S.decisions.length}</b><small>القرارات</small></div></div><div class="v8box"><h3>دورة النشاط</h3><p>مخطط: ${plans.length} — مبرمج/مسجل: ${acts.length} — منجز: ${acts.filter(a=>a.status==='منجز').length} — مؤجل: ${acts.filter(a=>a.status==='مؤجل').length} — ملغى: ${acts.filter(a=>a.status==='ملغى لأسباب').length} — خارج البرنامج: ${acts.filter(a=>a.source==='خارج البرنامج السنوي').length}</p><h3>الحالة المالية</h3><p>الرصيد الافتتاحي: ${money(m.opening||0)} — القبض: ${money(inc)} — الدفع: ${money(exp)} — الرصيد الحالي: ${money((m.opening||0)+inc-exp)}</p></div>`}
function v8settings(){return page('settings','الإعدادات وقواميس النظام',`<p class="notice">كل قائمة تستخدم في النماذج يجب أن تكون قابلة للتعديل من هنا. الإضافة إلى القاموس تنعكس على القوائم المرتبطة دون إعادة برمجة.</p><div class="v8bar"><select id="v8setkey">${Object.keys(window.settings).filter(k=>Array.isArray(window.settings[k])&&window.settings[k].every(x=>typeof x==='string')).map(k=>`<option value="${k}">${esc(k)}</option>`).join('')}</select><input id="v8setval" placeholder="عنصر جديد"><button onclick="v8AddSetting()">+ إضافة</button></div><div id="v8settable"></div><hr><h3>السنوات المالية</h3><div class="v8bar"><input id="v8newyear" type="number" value="${new Date().getFullYear()+1}"><button onclick="v8CreateYear()">إنشاء سنة</button></div><div id="v8yeartable"></div>`)}
function renderSettings(){let k=document.getElementById('v8setkey')?.value||'membershipTypes',arr=window.settings[k]||[];document.getElementById('v8settable').innerHTML=arr.map((x,i)=>`<div class="v8list"><span>${esc(x)}</span><button class="v8sm" onclick="v8RemoveSetting('${esc(k)}',${i})">حذف</button></div>`).join('')||'<p>لا توجد عناصر.</p>';document.getElementById('v8yeartable').innerHTML=years().map(y=>{let m=fy(y);return `<div class="v8list"><span>السنة ${y} — ${m.status==='closed'?'مغلقة':'مفتوحة'} — افتتاحي ${money(m.opening||0)} — إغلاق محسوب ${money(closeBal(y))}</span>${m.status!=='closed'&&y!=='2025'?`<button class="v8sm" onclick="v8CloseYear('${y}')">إغلاق السنة</button>`:''}</div>`}).join('')}
function v8AddSetting(){let k=v8setkey.value,v=v8setval.value.trim();if(!v)return;if(!Array.isArray(window.settings[k]))return;if(window.settings[k].includes(v))return alert('العنصر موجود');window.settings[k].push(v);save();renderAll();v8go('settings')}
function v8RemoveSetting(k,i){if(!confirm('حذف هذا العنصر من القاموس؟'))return;window.settings[k].splice(i,1);save();renderAll();v8go('settings')}
function v8CreateYear(){let y=String(v8newyear.value);if(!/^\d{4}$/.test(y))return;if(+y<2025)return alert('لا يمكن إنشاء سنة قبل 2025');let prev=years().filter(x=>+x<+y).sort((a,b)=>+b-+a)[0];if(prev&&S.yearMeta[prev]?.status!=='closed')return alert('أغلق السنة السابقة أولاً');fy(y);saveV8();renderAll();v8go('settings')}
function v8CloseYear(y){if(String(y)==='2025')return alert('2025 سنة تأسيسية موثقة ولا يعاد إغلاقها');let m=fy(y);if(m.status==='closed')return; m.status='closed';m.closing=closeBal(y);m.closedAt=new Date().toISOString();saveV8();log('إغلاق','سنة',y,m.closing);renderAll();v8go('settings')}
function v8gov(){return page('governance','الحوكمة والمتابعة',`<div class="v8tabs"><button onclick="v8MeetingForm()">+ اجتماع</button><button onclick="v8DecisionForm()">+ قرار</button><button onclick="v8TaskForm()">+ مهمة</button></div><div id="v8govtables"></div>`)}
function renderGov(){document.getElementById('v8govtables').innerHTML=`<h3>الاجتماعات</h3>${S.meetings.map(x=>`<div class="v8list"><b>${esc(x.title)}</b> — ${esc(x.date)} — ${esc(x.text||'')}</div>`).join('')||'<p>لا توجد اجتماعات.</p>'}<h3>القرارات</h3>${S.decisions.map(x=>`<div class="v8list"><b>${esc(x.title)}</b> — ${esc(x.date)} — ${esc(x.owner||'')}</div>`).join('')||'<p>لا توجد قرارات.</p>'}<h3>المهام</h3>${S.tasks.map(x=>`<div class="v8list"><b>${esc(x.title)}</b> — ${esc(x.date)} — ${esc(x.owner||'')} — ${esc(x.status)}</div>`).join('')||'<p>لا توجد مهام.</p>'}`}
function renderMail(){document.getElementById('v8intable').innerHTML=(S.incoming||[]).map(x=>`<div class="v8list"><b>${esc(x.ref)}</b> — ${esc(x.date)} — ${esc(x.party)} — ${esc(x.subject)} — ${esc(x.status)}</div>`).join('')||'<p>لا يوجد بريد وارد.</p>';document.getElementById('v8outtable').innerHTML=(S.outgoing||[]).map(x=>`<div class="v8list"><b>${esc(x.ref)}</b> — ${esc(x.date)} — ${esc(x.party)} — ${esc(x.subject)} — ${esc(x.status)}</div>`).join('')||'<p>لا يوجد بريد صادر.</p>';document.getElementById('v8corrtable').innerHTML=(S.correspondence||[]).map(x=>`<div class="v8list"><b>${esc(x.ref)}</b> — ${esc(x.date)} — ${esc(x.party)} — ${esc(x.subject)} — ${esc(x.status)}</div>`).join('')||'<p>لا توجد مراسلات.</p>'}
function renderDocs(){document.getElementById('v8doctable').innerHTML=S.documents.map(x=>`<div class="v8list"><b>${esc(x.number)}</b> — ${esc(x.date)} — ${esc(x.type)} — ${esc(x.title)} — ${esc(activityTitle(x.link))} <button class="v8sm" onclick="v8CreateOutgoingFromDoc('${x.id}')">إنشاء صادر</button></div>`).join('')||'<p>لا توجد وثائق.</p>'}
function v8CreateOutgoingFromDoc(id){let d=S.documents.find(x=>x.id===id);if(!d)return;let exists=S.outgoing.find(x=>x.documentId===id);if(exists)return alert('تم إنشاء الصادر لهذه الوثيقة مسبقاً');let o={id:'OUT-'+Date.now(),ref:d.number,date:d.date,party:'',subject:d.title,type:'إرسال وثيقة',owner:'',deadline:'',status:'مسجل',notes:'منشأ تلقائياً من الوثيقة',documentId:id};S.outgoing.push(o);saveV8();log('إنشاء صادر','بريد صادر',o.id,d.title);renderAll();v8go('outgoing')}
function renderDash(){let y=String(new Date().getFullYear()),m=fy(y),fs=(window.db.finance||[]).filter(f=>String(f.financialYear||f.date||'').slice(0,4)===y&&!f.voided),inc=fs.filter(f=>f.type!=='مصروف').reduce((s,f)=>s+(+f.amount||0),0),exp=fs.filter(f=>f.type==='مصروف').reduce((s,f)=>s+(+f.amount||0),0);document.getElementById('v8-dash').innerHTML=`<div class="v8cards"><div><b>${members().length}</b><small>الأعضاء</small></div><div><b>${S.activities.filter(a=>String(a.year)===y).length}</b><small>أنشطة ${y}</small></div><div><b>${money(m.opening||0)}</b><small>الرصيد الافتتاحي</small></div><div><b>${money((m.opening||0)+inc-exp)}</b><small>الرصيد الحالي</small></div></div><div class="v8box"><h3>مبدأ النظام</h3><p>التخطيط لا يساوي التنفيذ، والتقدير لا يساوي المصروف الفعلي، والعضو لا يساوي العضوية، والحركة المالية لا تسجل إلا مرة واحدة.</p></div>`}
function v8dash(){return page('dash','لوحة القيادة',`<div id="v8-dash"></div><div class="v8box"><h3>حالة المنصة</h3><p>السجل المحلي محفوظ على هذا الجهاز. النسخ السحابية متعددة المستخدمين والصلاحيات المركزية مرحلة لاحقة.</p></div>`)}
function v8reports2(){return v8reports()}
// Replace duplicate pages with final wrappers and patch renderer.
const oldRenderAll=renderAll; function renderAll2(){let main=document.getElementById('v8main');if(!main)return;main.innerHTML=v8dash()+v8members()+v8memberships()+v8planning()+v8activities()+v8finance()+v8assets()+v8mail()+v8incoming()+v8outgoing()+v8correspondence()+v8gov()+v8documents()+v8reports()+v8settings();bind();setTimeout(()=>{renderMemberTable();renderMemberships();renderPlanning();renderActivities();renderFinance();renderAssets();renderMail();renderGov();renderDocs();renderReports();renderSettings();renderDash()},0)}
function bind(){document.getElementById('v8mq')?.addEventListener('input',renderMemberTable);document.getElementById('v8msyear')?.addEventListener('change',renderMemberships);document.getElementById('v8mspack')?.addEventListener('change',renderMemberships);document.getElementById('v8pyear')?.addEventListener('change',renderPlanning);document.getElementById('v8ayear')?.addEventListener('change',renderActivities);document.getElementById('v8astatus')?.addEventListener('change',renderActivities);document.getElementById('v8asource')?.addEventListener('change',renderActivities);['v8fyear','v8fkind','v8fmember','v8factivity'].forEach(id=>document.getElementById(id)?.addEventListener('change',renderFinance));document.getElementById('v8eqstatus')?.addEventListener('change',renderAssets);document.getElementById('v8ryear')?.addEventListener('change',renderReports);document.getElementById('v8setkey')?.addEventListener('change',renderSettings)}
window.v8RenderFinance=renderFinance;window.v8RenderMemberships=renderMemberships;window.v8OpenMembership=v8OpenMembership;window.v8Backup=function(){let payload={schema:'8.1',exportedAt:new Date().toISOString(),db:window.db,settings:window.settings,packs:window.packs,integrated:S};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='نسخة_احتياطية_جمعية_الأفق_8.1.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.v8PrintReport=function(){let y=document.getElementById('v8ryear')?.value||new Date().getFullYear();let w=window.open('','_blank');w.document.write('<html dir="rtl"><head><meta charset="utf-8"><title>التقرير السنوي '+y+'</title><style>body{font-family:Arial;padding:25px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #777;padding:7px}h1{font-size:22px}</style></head><body><h1>التقرير السنوي لجمعية الأفق — '+y+'</h1>'+document.getElementById('v8report').innerHTML+'<p style="margin-top:60px">رئيس الجمعية: .................... &nbsp;&nbsp; أمين المال: ....................</p><script>window.print()<\/script></body></html>');w.document.close()};

// Public bridge for inline UI actions.
// The V8 interface uses inline onclick handlers, so functions defined inside
// this IIFE must be exposed explicitly on window for browser event handlers.
Object.assign(window, {
  v8Activity, v8ActivityForm, v8AddMember, v8AddParticipant, v8AddSetting,
  v8AssetDetail, v8AssetForm, v8ChangeAssetStatus, v8CloseYear,
  v8ConvertPlan, v8CreateOutgoingFromDoc, v8CreateYear, v8DecisionForm,
  v8DocForm, v8FinanceForm, v8Loan, v8MailForm, v8Maintenance,
  v8MeetingForm, v8Member, v8MemberEdit, v8OpenMembership, v8PlanForm,
  v8RemoveSetting, v8SaveActivity, v8SaveAsset, v8SaveDoc, v8SaveFinance,
  v8SaveMail, v8SaveNewMember, v8SavePlan, v8SaveSimple,
  v8SetActivityStatus, v8TaskForm
});

// annual financial protection: block direct legacy save when year closed.
const originalSaveFinance=window.saveFinance; window.saveFinance=function(){let y=document.getElementById('fFinancialYear')?.value||document.getElementById('fDate')?.value?.slice(0,4);if(y&&fy(y).status==='closed'){alert('السنة '+y+' مغلقة ولا يمكن تسجيل حركة مالية جديدة.');return;}return originalSaveFinance?.apply(this,arguments)};
// initialize 2025 and 2026 opening automatically from 2025 closing, without inventing member payments.
(function initYears(){if(!S.yearMeta['2025'])S.yearMeta['2025']={status:'closed',opening:0};let closing2025=closeBal('2025');if(!S.yearMeta['2026'])S.yearMeta['2026']={status:'open',opening:closing2025,createdAt:new Date().toISOString().slice(0,10)};else if(S.yearMeta['2026'].status!=='closed')S.yearMeta['2026'].opening=closing2025;saveV8()})();
// Build pages then show the new system.
window.renderAllV8=renderAll2;
setTimeout(()=>{try{shell();renderAll=renderAll2;renderAll2();v8go('dash')}catch(e){console.error('Afak V8 startup error',e);document.body.insertAdjacentHTML('beforeend',`<div style=\"position:fixed;inset:0;background:#fff;padding:24px;z-index:99999;font-family:Arial;direction:rtl\"><h2>تعذر تشغيل المنصة</h2><p>حدث خطأ أثناء تهيئة الواجهة. البيانات المحلية لم تُحذف.</p><details><summary>تفاصيل تقنية</summary><pre style=\"white-space:pre-wrap\">${esc(e&&e.stack||e)}</pre></details></div>`)}},50);
})();
